- README.md
Capitalize the project name, fix a broken link, and modify punctuation.
> Minor README fixes.

- glslc/README.asciidoc
- glslc/test/working_directory.py
Also mark incomplete features.
> Tests for -working-directory about multiple instances and position.

- .appveyor.yml
- README.md
- cmake/setup_build.cmake
The purpose of this pull request is to add configuration for Windows buildbot. Fixing the compilation and test error exposed by the Windows buildbot should be addressed in separate commits.
> Add AppVeyor configuration for building and testing on Windows.

- .travis.yml
- README.md
https://coveralls.io/github/google/shaderc
> Add coveralls code coverage configuration.

- libshaderc/src/shaderc_test.cc
And run clang-format on libshaderc/src/shaderc_test.cc.
> Make Compilation::result() const.

- DEVELOPMENT.howto.md
- README.md
Owned by dneto0 instead of antiagainst (at GitHub).
> Use a new AppVeyor project configuration

- .appveyor.yml
Update the location of pypa/get-pip.py, which has moved.
> Fix appveyor configuration.

- libshaderc/include/shaderc.h
Add 'null-terminated' in the blurb.
> add 'null-terminated'

- glslc/README.asciidoc
- glslc/src/file_compiler.cc
- glslc/src/file_compiler.h
- glslc/src/main.cc
- glslc/test/parameter_tests.py
- glslc/test/working_directory.py
- libshaderc_util/include/libshaderc_util/io.h
- libshaderc_util/src/io.cc
- libshaderc_util/src/io_test.cc
Disable working directory tests; Modified --help messages;
> Drop -working-directory command line option

- glslc/CMakeLists.txt
- glslc/README.asciidoc
- glslc/src/dependency_info.cc
- glslc/src/dependency_info.h
- glslc/src/file_compiler.cc
- glslc/src/file_compiler.h
- glslc/src/file_includer.cc
- glslc/src/file_includer.h
- glslc/src/main.cc
- glslc/test/expect.py
- glslc/test/option_dash_M.py
- glslc/test/parameter_tests.py
- libshaderc/src/shaderc.cc
Enable -M, -MD, -MF, -MT.
Still a work in progress.
> Add dependency info dumping handler to glslc to dump dependency info

- glslc/src/file_includer.h
- libshaderc/src/shaderc.cc
- libshaderc/src/shaderc_cpp_test.cc
- libshaderc/src/shaderc_test.cc
- libshaderc_util/src/compiler_test.cc
- libshaderc_util/src/format_test.cc
Issues include missing "explicit" on constructors, missing
initialization for struct members, unused variables, etc..
> Fix various issues reported by cppcheck.

- CMakeLists.txt
- README.md
This can be set by an external project or also in the configuration
itself.
> Added an option to use the shared CRT.

- glslc/test/glslc_test_framework.py
- utils/add_copyright.py
- utils/update_build_version.py
* Use print_function from __future__ to tackle the print syntax
change.
* In Python3 str and bytes are no longer the same thing. Need
proper decode.
Counterpart for https://github.com/KhronosGroup/SPIRV-Tools/issues/144
> Improve Python3 Compatibility

- utils/update_build_version.py
When the given directory is not inside a git managed project,
`describe()` returns a `str` instance instead of `bytes` instance
in Python3, which will case problem when calling `decode()` on it.
Similar to https://github.com/KhronosGroup/SPIRV-Tools/pull/147
> Fix corner case and return str in describe() as said in the blurb.

- utils/build.py
It seems that os.putenv somehow doesn't work on Unix.
Also use os.pathsep.join() instead of "+ os.pathsep +".
Also run pyformat.
> Use os.environ instead of os.putenv in build.py.

- cmake/utils.cmake
- libshaderc/src/shaderc_cpp_test.cc
- libshaderc/src/shaderc_test.cc
- libshaderc_util/include/libshaderc_util/mutex.h
Also fixed cmake target if mingw is present.
> Removed the remaining threaded tests.

- third_party/CMakeLists.txt
This allows us to specify the location of third party projects
if we would rather have them somewhere other than third_party/
> Allowed third_party projects to be located elsewhere.

- libshaderc_util/src/compiler.cc
Depends on https://github.com/KhronosGroup/SPIRV-Tools/pull/165.
> Give spvContextCreate() a target environment.

- glslc/README.asciidoc
@antiagainst @AWoloszyn @dneto0 @Qining PTAL
> Add -I to the glslc synopsis.

- glslc/src/main.cc
- glslc/test/option_dashdash_version.py
Shaderc response to https://github.com/KhronosGroup/SPIRV-Tools/pull/178.
@antiagainst @AWoloszyn @dneto0 @Qining PTAL.
> Remove revision from SPV_ENV_*.

- third_party/Android.mk
@dneto0 @AWoloszyn @antiagainst @Qining PTAL
> Add .inc grammar generation to Android.mk.

- glslc/src/file_compiler.cc
- glslc/src/shader_stage.cc
- glslc/test/assembly.py
- glslc/test/expect.py
- glslc/test/glslc_test_framework.py
- libshaderc/CMakeLists.txt
- libshaderc/include/shaderc/shaderc.h
- libshaderc/include/shaderc/shaderc.hpp
- libshaderc/src/common_shaders_for_test.h
- libshaderc/src/shaderc.cc
- libshaderc/src/shaderc_cpp_test.cc
- libshaderc/src/shaderc_private.h
- libshaderc/src/shaderc_test.cc
- libshaderc_util/CMakeLists.txt
- libshaderc_util/include/libshaderc_util/spirv_tools_wrapper.h
- libshaderc_util/src/compiler.cc
- libshaderc_util/src/spirv_tools_wrapper.cc
Addresses #80.
TODO: more tests for command-line.
> Add assembling into shaderc.

- third_party/Android.mk
@antiagainst @AWoloszyn @dneto0 @Qining PTAL.
> Add rules to create build-version.inc on Android.

- third_party/Android.mk
Needed to update google/glslang to KhronosGroup/glslang.
> Register new files appearing in glslang into Android.mk.

- CMakeLists.txt
- cmake/utils.cmake
- glslc/test/CMakeLists.txt
- libshaderc/CMakeLists.txt
- third_party/CMakeLists.txt
Together with https://github.com/KhronosGroup/SPIRV-Tools/pull/301.
> Fix SHADERC_SKIP_TESTS configuration to actually skip all tests.

- third_party/Android.mk
This CL is to correspond with https://github.com/KhronosGroup/SPIRV-Tools/pull/400
> Add util/parse_number.cpp to third_party/Android.mk

- Android.mk
- libshaderc/Android.mk
- libshaderc_util/Android.mk
- third_party/Android.mk
Requires https://github.com/KhronosGroup/SPIRV-Tools/pull/424
> Add the SPIRV-Tools-opt library into Android.mk.

- README.md
Describe why it exists: what does Shaderc add on top?
> Clarify Shaderc wraps around other tools

- utils/copy-tests-if-necessary.py
Before, we were catching too-broad a set of exceptions.
On Windows sometimes you might not be able to remove the
original directory, e.g. since a process might be running
in that directory.  That can lead to spurious test failures where
tests would run but compare to stale base results.
Also:
- sort the test file list, for nicer debugging.
- fix linting warnings for unused variables.
> When copying tests, only catch ENOENT exception

- third_party/Android.mk
Goes with https://github.com/KhronosGroup/SPIRV-Tools/pull/444
> Add source/parsed_operand.cpp to SPIRV-Tools

- third_party/Android.mk
Tested with Anrdoid NDK r10e and r14-beta1.
> Add -Werror to Android build

- CHANGES
- glslc/src/dependency_info.cc
- glslc/src/file_compiler.cc
- glslc/src/file_compiler.h
- glslc/test/error_no_object.py
- glslc/test/expect.py
- libshaderc_util/include/libshaderc_util/io.h
- libshaderc_util/src/io.cc
- libshaderc_util/src/io_test.cc
Fixes https://github.com/google/shaderc/issues/289
> Don't generate an output file if compilation fails

- libshaderc/CMakeLists.txt
Okay, missing headers in previous PRs.
> Install shaderc header files.

- README.md
Also fix a typo in a different heading.
> Describe the known-good branch

- libshaderc/src/shaderc.cc
- libshaderc/src/shaderc_test.cc
Fixes https://github.com/google/shaderc/issues/308
> Fix include error message when no options object

- third_party/Android.mk
Added https://github.com/KhronosGroup/SPIRV-Tools/pull/585
to shaderc Android.mk.
> Added extension enum, mapping autogen to android

- third_party/Android.mk
File was added to SPIRV-Tools in
https://github.com/KhronosGroup/SPIRV-Tools/commit/1e309af80a4486f8826b66a4ea37777ed874ff87
> Added compact_ids_pass.cpp to Android.mk

- cmake/utils.cmake
Fixes https://github.com/google/shaderc/issues/334
> Avoid noexcept-type in GCC 7.1 for test code

- glslc/test/assembly.py
Needed to update to the current head of glslang https://github.com/KhronosGroup/glslang/commit/d9b08d5c3db62317c98a135e1c2cc616f1bafc61
> Fix test to update glslang

- libshaderc_util/src/counting_includer_test.cc
This is caught by leak checks in Clang 3.6 address sanitizer.
This is just one of many memory leaks in our tests.  :-(
> Avoid mem leaks in counting includer test

- glslc/src/main.cc
> Shorten arg checking for -f*-binding-base

- CHANGES
- glslc/test/assembly.py
- glslc/test/option_std.py
- libshaderc_util/CMakeLists.txt
- libshaderc_util/include/libshaderc_util/version_profile.h
- libshaderc_util/src/version_profile_test.cc
Requires updated sources from KhronosGroup/glslang
> Support GLSL 4.6 and ESSL 3.2

- libshaderc_util/include/libshaderc_util/counting_includer.h
Should fix ASAN failures in the CountingIncluderTest:
The ConcreteCountingIncluder include delegate is not safe
to call concurrently.  It's just simpler/nicer for the base
class to protect us in this way.
> Serialize inclusions by the CountingIncluder

- .appveyor.yml
- README.md
OK. Authentication problems again.  I give up. Fix the master first.
> Appveyor: Stop deploying to BinTray

- third_party/CMakeLists.txt
This makes glslang link to SPIRV-Tools for optimiztion correctly.
> Include SPIRV-Tools before glslang

- .travis.yml
Fixes https://github.com/google/shaderc/issues/409
> Travis CI: install pip and set clone depth to 1

- .appveyor.yml
Also, stop after first failure.
> Skip Debug builds for VS 2013 and VS 2015

- glslc/src/main.cc
- glslc/test/parameter_tests.py
- libshaderc/include/shaderc/shaderc.h
- libshaderc/include/shaderc/shaderc.hpp
- libshaderc/src/shaderc.cc
- libshaderc_util/include/libshaderc_util/compiler.h
- libshaderc_util/src/compiler.cc
- libshaderc_util/src/compiler_test.cc
See #369 
(Followup to #423 but with expectations corrected for glslc --help output --dneto0)
> Add -fauto-map-locations option

- glslc/README.asciidoc
Added to the "Code generation options" section.
> Update glslc README for -fauto-map-locations

- glslc/test/assembly.py
- glslc/test/expect.py
- glslc/test/option_dash_cap_O.py
- libshaderc/src/common_shaders_for_test.h
Make OpArrayLength result type be an integer with signedness of 0.
> Glslang generator version 5

- third_party/CMakeLists.txt
> Link SPIRV-Tools into Glslang

- glslc/test/assembly.py
- glslc/test/expect.py
- glslc/test/option_dash_cap_O.py
- libshaderc/src/common_shaders_for_test.h
Requires a corresponding refresh of google/glslang
> Update to Glslang generator version 7

- kokoro/windows/build.bat
- kokoro/windows/build_debug_2017.bat
- kokoro/windows/build_release_2013.bat
- kokoro/windows/build_release_2015.bat
- kokoro/windows/build_release_2017.bat
- kokoro/windows/continuous_debug_2017.cfg
- kokoro/windows/continuous_release_2013.cfg
- kokoro/windows/continuous_release_2015.cfg
- kokoro/windows/continuous_release_2017.cfg
- kokoro/windows/presubmit_debug_2017.cfg
- kokoro/windows/presubmit_release_2013.cfg
- kokoro/windows/presubmit_release_2015.cfg
- kokoro/windows/presubmit_release_2017.cfg
After this change, we should have
VS2017 Debug and Release
VS2015 Release
VS2013 Release
> WIP: Update Windows kokoro bots.

- CHANGES
LGTM.  Mainly I want to see all the bots pass.
> Update CHANGES.  (E.g. Added NV Turing extensions)

- CMakeLists.txt
> Set the CMake C++ standard to C++11

- BUILD.gn
> BUILD.gn: only use complete_static_lib on mac

- libshaderc/src/common_shaders_for_test.h
- libshaderc/src/shaderc.cc
- libshaderc/src/shaderc_test.cc
Fixes a bug inferring mesh shaders from .mesh file suffix.
> Add unit tests for mesh and task shaders

- kokoro/windows/build.bat
Using %ERRORLEVEL% inside an IF...() block captures the variable's
value as the block is entered.  Use !ERRORLEVEL! so error handling
works as expected.
Use %ERRORLEVEL% NEQ 0 in case of negative values.
Ensure zero is returned if tests passed, regardless of cleanup errors.
Refactor cmake flags to reduce duplication.
> Fix Windows test script return value.

- kokoro/linux/build.sh
The symbolizer was not being found.
Also don't use sudo and mess up /usr/bin.
> Fix ASAN build.

- libshaderc_spvc/CMakeLists.txt
- third_party/CMakeLists.txt
SPIRV-Cross needs to be told when exceptions are off.
> Fix build with exceptions off.

- BUILD.gn
> BUILD.gn: fix build error on is_component_build=true

- DEPS
This CL rolls the GLSLang DEPS file forward to pickup the memory leak
fixes.
> Roll GLSLang.

- libshaderc_spvc/src/spvc_c_smoke_test.c
Free some memory we forgot to free.
> Fix spvc_c_smoke_test.

- libshaderc_spvc/src/spvc_c_smoke_test.c
Free more memory we forgot to free.
> Fix spvc_c_smoke_test some more.

- CMakeLists.txt
- libshaderc/include/shaderc/env.h
- spvc/.clang-format
- spvc/CMakeLists.txt
- spvc/README.asciidoc
- spvc/src/main.cc
- spvc/test/CMakeLists.txt
- spvc/test/run_spirv_cross_tests.py
Initial version of command line tool 'spvc' which is a wrapper around
spirv-cross.  Testing is the same as for spirv-cross, but not all
pass yet.
> Add spvc command line tool and tests.

- kokoro/linux/presubmit_clang_asan.cfg
Run ASAN test on every uploaded change.
> Add presubmit_clang_asan bot.

- libshaderc_spvc/include/shaderc/spvc.h
- libshaderc_spvc/include/shaderc/spvc.hpp
- libshaderc_spvc/src/spvc.cc
- spvc/src/main.cc
- spvc/test/run_spirv_cross_tests.py
Add the MSL and HLSL SPIRV-Cross tests.
> spvc: Add MSL and HLSL tests.

- BUILD.gn
Add missing files and tell libshaderc_spvc to include from libshaderc.
> Fix gn build.

- BUILD.gn
Fix issues found by gn check and gn format.
Remove files that don't exist and add files libshaderc_spvc depends on.
> Satisfy gn check.

- third_party/CMakeLists.txt
> Disable running re2 tests

- CMakeLists.txt
- spvc/test/run_spirv_cross_tests.py
- utils/add_copyright.py
- utils/build.py
- utils/git-sync-deps
- utils/update_build_version.py
This also includes a little code cleanup, so I see less complaints about style
violations.
Fixes #620
> Convert to requiring Python 3

- spvc/test/run_spirv_cross_tests.py
These tests should be hermetic from each other and there is 1.5k of them, so
lets speed things up
Fixes #611
> Run spirv-cross tests in parallel

- spvc/test/run_spirv_cross_tests.py
- utils/add_copyright.py
- utils/build.py
- utils/copy-tests-if-necessary.py
- utils/git-sync-deps
- utils/update_build_version.py
> Run pyformat on utils and test scripts

- spvc/test/run_spirv_cross_tests.py
> Add flag to allow filtering tests cases being run

- update_shaderc_sources.py
Also ran pyformat to make script consistent.
Fixes #529
> Convert script to be Python 3

- DEPS
This pulls in changes to WebGPU<->Vulkan transformations.
> Roll spirv-tools dependency

- libshaderc/include/shaderc/env.h
- libshaderc/include/shaderc/status.h
- libshaderc_spvc/Android.mk
- libshaderc_spvc/CMakeLists.txt
- libshaderc_spvc/include/shaderc/spvc.h
- libshaderc_spvc/include/shaderc/spvc.hpp
- libshaderc_spvc/src/common_shaders_for_test.h
- libshaderc_spvc/src/spvc.cc
- libshaderc_spvc/src/spvc_smoke_test_util.c
- libshaderc_spvc/src/spvc_smoke_test_util.h
- libshaderc_spvc/src/spvc_test.cc
- libshaderc_spvc/src/spvc_webgpu_c_smoke_test.c
- libshaderc_spvc/src/spvc_webgpu_cpp_test.cc
- libshaderc_spvc/src/spvc_webgpu_test.cc
- spvc/src/main.cc
> Add ability to transform spvc input from WebGPU SPIR-V

- libshaderc/include/shaderc/status.h
- libshaderc_spvc/include/shaderc/spvc.h
- libshaderc_spvc/include/shaderc/spvc.hpp
- libshaderc_spvc/src/spvc.cc
- libshaderc_spvc/src/spvc_smoke_test_util.c
- libshaderc_spvc/src/spvc_webgpu_cpp_test.cc
- libshaderc_spvc/src/spvc_webgpu_test.cc
- spvc/src/main.cc
- spvc/test/run_spirv_cross_tests.py
> Re-write environment control flags to be consistent

- README.md
>  Add details of spvc to README.md

- Dockerfile
- glslc/test/glslc_test_framework.py
Also ran 2to3 on one file that had some Python2-isms.
Fixes #666
> Update Dockerfile to use Python 3

- utils/roll-deps
> Add script to generate manual roll patch

- utils/roll-deps
Primarily makes the script less fragile wrt invocation location.
Also cleans up some style things.
> Import improvements to DEPS roll script

- utils/git-sync-deps
- utils/roll-deps
Adding in passing through args for roll-deps
Using non-greedy matching in git-sync-deps
> Import script fixes from other SPIRV related repos

- BUILD.gn
Sorry about the noise. GN configs can be surprising :-(
> Fix BUILD.gn for Chromium build.

- spvc/test/run_spirv_cross_tests.py
This patch refactors calls to system libraries that might throw to
catch and return a failure instead of crashing.
This makes debugging easier when tests fail due to invalid spirv, etc
since now an unexpected failure is reported instead of a stack trace.
This also lays some of the ground work for refactoring logging, by
having a path for command output to travel through.
Catching is performed at the call site, instead at the top of the work
function, so that catching ca be specific to the exceptions that are
used to indicate expected failures. Other exceptions in this script
suggest a bug or programming error.
Fixes #740
> Catch low level exceptions instead of crash

- spvc/test/run_spirv_cross_tests.py
Also ran pyformat on the script.
Fixes #737
> Remove old logging infra from run_spirv_cross_tests.py

- known_good.json
Verified with an NDK build, and unit tests on Windows
> known-good: Update all components

- spvc/test/run_spirv_cross_tests.py
Avoid a complaint by a linter.
> Be more pythonic about "not in"

- CMakeLists.txt
- glslc/src/dependency_info.h
- glslc/src/file_compiler.h
- glslc/src/file_includer.h
- libshaderc/src/shaderc_test.cc
Cleans up additional incidents of this code smell.
Fixes #769
> Turn on warnings on about missing semi-colons

- libshaderc_spvc/include/shaderc/spvc.h
- libshaderc_spvc/include/shaderc/spvc.hpp
- libshaderc_spvc/src/spvc.cc
- spvc/src/main.cc
> spvc: Add option to inject code to enforce robust-buffer-access

- CMakeLists.txt
- utils/update_build_version.py
Not all build systems will want to place the output from
update_build_version.py in the same location.  I updated the script to
take the output file a parameter.
> Have update_build_version.py new parameter

- spvc/test/known_failures
- spvc/test/run_spirv_cross_tests.py
> Add --update_known_failures to spvc test script

- spvc/test/run_spirv_cross_tests.py
> Add logging missing failures to spvc test script

- CMakeLists.txt
- libshaderc_spvc/CMakeLists.txt
- libshaderc_spvc/src/spvc_private.cc
- libshaderc_spvc/src/spvcir_pass.cpp
- libshaderc_spvc/src/spvcir_pass.h
Adds a test spirv opt pass to HLSL compiler 
If turned on, this pass prints the given source
> spvc: Add an empty opt pass

- libshaderc_spvc/CMakeLists.txt
- libshaderc_spvc/src/spvcir_pass.h
> Fix up use of private spirv-tools headers.

- CMakeLists.txt
- libshaderc_spvc/src/spvc_private.cc
- libshaderc_spvc/src/spvcir_pass.cc
- libshaderc_spvc/src/spvcir_pass.h
- spvc/test/CMakeLists.txt
- spvc/test/reference/shaders-hlsl-no-opt/asm/vert/trivial_shader.asm.vert
- spvc/test/run_spirv_cross_tests.py
- spvc/test/run_spirv_cross_tests_wrapper.sh
- spvc/test/shaders-hlsl-no-opt/asm/vert/trivial_shader.asm.vert
This is the first PR in a series of PRs for parsing and generating spiv-cross-ir using an opt pass.
fixes issue #651
> spvc parser for a trivial shader

- spvc/test/run_spirv_cross_tests.py
> Refactor file reading code into common utility method

- libshaderc_spvc/include/spvc/spvc.h
- libshaderc_spvc/include/spvc/spvc.hpp
- libshaderc_spvc/src/spvc.cc
- libshaderc_spvc/src/spvc_cpp_test.cc
- libshaderc_spvc/src/spvc_private.cc
- libshaderc_spvc/src/spvc_private.h
- libshaderc_spvc/src/spvc_smoke_test_util.c
- libshaderc_spvc/src/spvc_test.cc
- libshaderc_spvc/src/spvc_webgpu_cpp_test.cc
- libshaderc_spvc/src/spvc_webgpu_test.cc
- spvc/src/main.cc
> Move spirv_cross state out of result and rename opaque state handle

- libshaderc_spvc/src/spvcir_pass.cc
- utils/add_copyright.py
> Correct Unicode issues with add_copyright.py

- libshaderc_spvc/src/spvcir_pass.cc
- libshaderc_spvc/src/spvcir_pass.h
- libshaderc_spvc/src/spvcir_test.cc
Add support for:
- OpConstantFalse
- OpConstantComposite
- OpConstantNull
- OpSpecConstantTrue
- OpSpecConstantFalse
- OpSpecConstantComposite
- OpSpecConstantOp
- OpExtInst
- OpFunctionParameter
> Add spvc parser support for all OpConstant.* and OpSpecConstant.*

- libshaderc_spvc/include/spvc/spvc.h
- libshaderc_spvc/include/spvc/spvc.hpp
- libshaderc_spvc/src/spvc.cc
Need to add ability to enable/disable PointSize builtin and set buffer
size buffer index.
Fixes #891 & #892
> Add access to MSL options needed by Dawn

- libshaderc_spvc/src/spvcir_pass.cc
- libshaderc_spvc/src/spvcir_test.cc
I'll add test for OpSelectionMerge, OpSwitch and OpLoopMerge in the next PR.
> Add spvc parser support for control flow instructions

- libshaderc_spvc/src/spvcir_pass.cc
- libshaderc_spvc/src/spvcir_test.cc
OpUndef, OpString, OpMemberDecorate, OpDecorationGroup, OpLine, OpNoLine,
> Add spvc parser support for OpUndef, OpString, OpMemberDecorate, OpDecorationGroup, OpLine, and OpNoLine

- libshaderc_spvc/src/spvcir_pass.cc
- libshaderc_spvc/src/spvcir_test.cc
OpGroupDecorate
OpGroupMemberGecorate
OpDecorateStringGOOGLE
OpMemberDecorateStringGOOGLE
> Add spvc parser support for OpGroupDecorate, OpGroupMemberGecorate, OpDecorateStringGOOGLE, and OpMemberDecorateStringGOOGLE

- BUILD.gn
- CMakeLists.txt
- libshaderc_spvc/CMakeLists.txt
- libshaderc_spvc/include/spvc/spvc.h
- libshaderc_spvc/include/spvc/spvc.hpp
- libshaderc_spvc/src/spvc.cc
- libshaderc_spvc/src/spvc_private.cc
- libshaderc_spvc/src/spvc_private.h
- spvc/src/main.cc
- spvc/test/CMakeLists.txt
- spvc/test/run_spirv_cross_tests.py
> Convert spvc parser flag from build time to runtime

- libshaderc_spvc/include/spvc/spvc.h
- spvc/src/main.cc
> Convert spvc return codes to their own enum

- libshaderc_spvc/include/spvc/spvc.h
- libshaderc_spvc/include/spvc/spvc.hpp
- libshaderc_spvc/src/spvc.cc
- libshaderc_spvc/src/spvc_private.cc
- libshaderc_spvc/src/spvc_private.h
> Add missing APIs for HLSL support in Dawn - set_decoration

- libshaderc_spvc/include/spvc/spvc.h
- libshaderc_spvc/include/spvc/spvc.hpp
- libshaderc_spvc/src/spvc.cc
> Add missing APIs for GLSL in Dawn

- libshaderc_spvc/include/spvc/spvc.h
- libshaderc_spvc/src/spvc_private.cc
> Convert enum from BLOCK_STYLE to snake_style

- libshaderc_spvc/include/spvc/spvc.h
- libshaderc_spvc/include/spvc/spvc.hpp
- libshaderc_spvc/src/spvc.cc
> Adding in missing APIs for MSL support in Dawn

- glslc/README.asciidoc
> Fix spelling of -finvert-y in doc

- README.md
> Add reference to Go bindings in README.md

- libshaderc_spvc/include/spvc/spvc.h
- libshaderc_spvc/include/spvc/spvc.hpp
- libshaderc_spvc/src/spvc.cc
> Implement Reflection API needed by Dawn

- glslc/README.asciidoc
> Fix incorrect casing on flags in docs

- libshaderc_spvc/src/spvc.cc
> Use the correct comparison when checking for not MSL

- known_good.json
Updates Glslang, SPIRV-Tools, Shaderc.
Refresh re2, googletest, effcee
> Update for Vulkan 1.2 support

- libshaderc_spvc/src/spvc.cc
> Change call in shaderc_spvc_needs_buffer_size_buffer to be correct

- glslc/README.asciidoc
> Add documentation for Vulkan 1.2 and SPIR-V 1.5

- libshaderc_spvc/include/spvc/spvc.h
- libshaderc_spvc/src/spvc.cc
> Add reflection support for storage textures

- libshaderc_spvc/include/spvc/spvc.h
- libshaderc_spvc/src/spvc.cc
> Add support for storage texture format reflection

- libshaderc_spvc/src/spvc.cc
> Extract texture dimension for storage textures

- DEPS
git log 8e26c5f50..ad1b588de --date=short --no-merges --format='%ad %ae %s'
2020-03-30 cepheus@frii.com Bump revision.
2020-03-30 cepheus@frii.com Fix #2163: improve comments for addProcess() and the preamble.
2020-03-30 ntfs.hard@gmail.com printf format
2020-03-30 ntfs.hard@gmail.com unused var
2020-03-30 ntfs.hard@gmail.com bitwise on boolean
2020-03-30 ntfs.hard@gmail.com opposite inner condition
2020-03-27 greg@lunarg.com Update spirv-tools known_good to latest stable
2020-03-26 neslisah.torosdagli@amd.com accelerationStructureEXT - issue #2152
2020-03-26 neslisah.torosdagli@amd.com accelerationStructureEXT - issue #2152
2020-03-26 neslisah.torosdagli@amd.com pass by reference updates
2020-03-26 neslisah.torosdagli@amd.com pass-by-reference updates
2020-03-25 gcmn@google.com Add …
> Roll glslang dependency to SDK-candidate tag

- DEPS
- libshaderc_spvc/include/spvc/spvc.h
- libshaderc_spvc/include/spvc/spvc.hpp
- libshaderc_spvc/src/spvc.cc
Also sets the default to true, since in most cases this is what we want.
Fixes #1023
> Add knob to control force_zero_initialized_variables

- known_good.json
> Update Glslang to SDK-candidate-2

- README.md
> Add another warning sign about unsupported downloads

- libshaderc_spvc/include/spvc/spvc.h
- libshaderc_spvc/include/spvc/spvc.hpp
- libshaderc_spvc/src/spvc.cc
> Add support for options.hlsl.nonwritable_uav_texture_as_srv

- README.md
> Add .NET bindings to README.md

- libshaderc/src/shaderc.cc
- libshaderc/src/shaderc_private.h
- libshaderc_util/include/libshaderc_util/compiler.h
- libshaderc_util/src/compiler.cc
- libshaderc_util/src/compiler_test.cc
> Remove Singleton pattern around access to glslang

- known_good.json
> Update glslang, spirv-headers, spirv-tools

- utils/roll-deps
PTAL, this is in anticipation of some DEPS moving to using origin/main.
> Add support for different default/trunks in roll-deps

- glslc/README.asciidoc
- glslc/src/main.cc
- glslc/test/parameter_tests.py
- spvc/src/main.cc
This is slightly more friendly
> glslc and spvc understand -h as the same as --help

- .gitignore
- libshaderc/src/shaderc_cpp_test.cc
- libshaderc/src/shaderc_test.cc
- libshaderc_util/include/libshaderc_util/file_finder.h
This CL updates some language usage to be in line with the Android
respectful code guidelines [1].
1- https://source.android.com/setup/contribute/respectful-code
> Update some language usage.

- BUILD.gn
- build_overrides/shaderc.gni
> Adding back non-spvc BUILD.gn that I accidentally nuked

- known_good.json
spirv-headers - top of tree 2020-09-28
glslang - top of tree 2020-09-28
spirv-tools - v2020.5
shaderc - v2020.3
effcee - still at v2019.1
> known-good:  Update tooling

- DEPS
This works around issue 1149, prolems with VisualStudio 2015
> Roll back googletest to earlier version

- libshaderc/include/shaderc/shaderc.hpp
It looks like this is needed to unblock https://github.com/google/amber/pull/924
> Replace C-style cast with static_cast

- known_good.json
Tested with Android NDK build.
> Include Vulkan raytracing fixes

- libshaderc_util/include/libshaderc_util/message.h
- libshaderc_util/src/message.cc
- libshaderc_util/src/message_test.cc
> Improve file+line parsing from Glslang messages

- CMakeLists.txt
Signed-off-by: Jose Quaresma <quaresma.jose@gmail.com>
> cmake: add option to skip build the examples

- CONTRIBUTORS
- glslc/src/main.cc
- glslc/test/option_fauto_combined_image_sampler.py
- glslc/test/option_fauto_sampled_textures.py
- glslc/test/parameter_tests.py
- libshaderc/include/shaderc/shaderc.h
- libshaderc/include/shaderc/shaderc.hpp
- libshaderc/src/shaderc.cc
- libshaderc_util/include/libshaderc_util/compiler.h
- libshaderc_util/src/compiler.cc
Fixes up and supercedes #1181 
Thanks @Rob2309 for doing most of the work for this.
> Expose -fauto-combine-image-sampler compile option

- README.md
> Add external Common Lisp bindings to README.md

- DEPS
> Update DEPS: glslang, spirv-tools, spirv-headers

- CHANGES
- DEPS
This must be submitted as two separate commits, so I can tag the first one as v2021.3
> Finalize v2021.3, start v2021.4-dev

- utils/add_copyright.py
Fix similar to https://github.com/google/shaderc/commit/10530a08bdc5a3fb627746f64bc7e0a8b18819f8
> Fix for missing copyright in glslang

- known_good.json
> Update SPIRV-Tools, SPIRV-Headers, Glslang

- known_good.json
Use the top-of-tree GitHub commits from 2022-06-01
> Update glslang, SPIRV-Tools, SPIRV-Headers, shaderc

- known_good.json
Shaderc v2022.3
Glslang GitHub master 2022-10-12
SPIRV-Headers GitHub master 2022-10-12
SPRIV-Tools v2022.4
> Update Shaderc, Glslang, SPIRV-Tools, SPIRV-Headers

- known_good.json
Includes bugfix https://github.com/KhronosGroup/SPIRV-Tools/pull/5049
> Update to updated SPIRV-Tools v2023.1

- kokoro/ndk-build/build-docker.sh
- kokoro/ndk-build/build.sh
Google internal bug b/279225905
> kokoro: convert ndk-build to use docker

- CHANGES
- DEPS
> Finalize v2023.4, start v2023.5-dev

- android_test/jni/Application.mk
> Increase Android API level for test project

- DEPS
Up to https://github.com/KhronosGroup/glslang/pull/3264
- Fix Android build for r25 NDK
> Update Glslang in DEPS

- DEPS
- glslc/test/line.py
- glslc/test/option_dash_D.py
- glslc/test/option_dash_E.py
- glslc/test/option_dash_M.py
- libshaderc/src/shaderc_cpp_test.cc
- libshaderc/src/shaderc_test.cc
Updates all of the dependencies. Glslang has changed the format of some of
their outputs. Tests have been updated to account for that.
> Roll deps & fix tests

- known_good.json
Glslang GitHub top of tree 2024-03-09
SPIRV-Headers GitHub top of tree 2024-03-09
SPIRV-Tools v2024.1.rc1
Shaderc v2024.0
> Update dependencies: Shaderc v2024.0

- DEPS
- third_party/CMakeLists.txt
This needs https://github.com/KhronosGroup/glslang/pull/3508 to be effective
Fixes: #1396
> Propagate test/install options to Glslang

- known_good.json
Shaderc v2024.1
Glslang GitHub 2024-04-30
SPIRV-Tools v2024.2.rc1
SPIRV-Headers GitHub 2024-04-30
Effcee GitHub 2024-04-30
> Update for Shaderc v2024.1

- README.md
- downloads.md
> Remove VS2017 from README and download links

- known_good.json
Shaderc v2024.2
Glslang: top of tree 2024-06-21
SPIRV-Header: top of tree 2024-06-21
SPIRV-Tools: v2024.3.rc1
> Update for Shaderc v2024.2

- CHANGES
- DEPS
Includes support for Vulkan 1.4
> Update shaderc, finalizing Shaderc v2024.4

- kokoro/android-release/build.sh
- kokoro/linux/build.sh
- kokoro/ndk-build/build.sh
> kokoro: linux: use cpp-builder instead of radial-build
