google/shaderc

README.md
glslc/README.asciidoc
glslc/src/file_compiler.h
glslc/src/main.cc
libshaderc_util/include/libshaderc_util/compiler.h

* Sort command line options in `main.c` to make it consistent with the manual.
* Sort and group fields in compiler-related classes.
* Add missing blurbs for some fields.
* Add the `-I` option in `glslc` manual.

Sort command line options and class fields

---

glslc/src/main.cc
glslc/test/option_std.py

When a command line option ends with an equal sign, it's argument
is what follows that equal sign, even if it's empty.

Fix a problem in command line option parsing.

---

glslc/README.asciidoc
glslc/src/file_compiler.cc
glslc/src/file_compiler.h
glslc/src/main.cc
glslc/test/expect.py
glslc/test/parameter_tests.py
glslc/test/working_directory.py
libshaderc_util/include/libshaderc_util/io.h
libshaderc_util/src/io.cc
libshaderc_util/src/io_test.cc

This patch enables `glslc` to accept `-working-directory` as an option.
Input and output files are resolved against the working directory if
necessary. Setting working directory with the existence of the `#include`
directive is not implemented yet.

Support for -working-directory

---

README.md

Describe the relation to KhronosGroup/glslang.
We're not forking the glslang project!

Clarify Shaderc readme.

---

Android.mk
README.md
android_test/Android.mk
android_test/jni/Android.mk
android_test/jni/Application.mk
android_test/test.cpp
cmake/setup_build.cmake
libshaderc/Android.mk
libshaderc/src/shaderc_cpp_test.cc
libshaderc_util/Android.mk
libshaderc_util/src/version_profile.cc
third_party/Android.mk
third_party/CMakeLists.txt

This allows shaderc to be built by both using
android.cmake as well as native Android.mk build files.

Added Android.mk and Android cmake build support.

---

.appveyor.yml

There is an infinite loop when testing for the debug configuration
on Windows. We don't want to waste AppVeyor resources on this issue
for every commit. Will bring back once the infinite loop is solved.

Turn off debug build on Window temporarily

---

libshaderc_util/src/io_test.cc

We use C++ `std::string` for handling paths. Library functions based
on `std::string` doesn't play nicely with Unicode.

Remove Unicode characters from path tests.

---

glslc/src/file_compiler.cc
glslc/test/expect.py
libshaderc_util/include/libshaderc_util/io.h

Also, update the glslc test framework so that any test will fail if the subprocess was terminated by a signal.  This is especially important to distinguish for a test where the subprocess is expected to exist with non-zero status code.

glslc: avoid crash on failure to open the output file stream

---

libshaderc/src/shaderc_cpp_test.cc
libshaderc/src/shaderc_test.cc
libshaderc_util/src/compiler.cc

Glslang has been migrated to use the Rev. 31 `spirv.hpp` header.
`GLSL450Lib.h` was replaced by `GLSL.std.450.h`.

Catch up with glslang development

---

.travis.yml

We set `CC` to `gcc-4.8` previously; so checking whether `CC` is `gcc`
doesn't work any more.

Travis CI: test correct CC for uploading coverage report.

---

libshaderc/include/shaderc.h
libshaderc/src/shaderc.cc
libshaderc/src/shaderc_test.cc

Currently only vertex and fragment shader types are exposed; this adds
mappings for the remainder

Add missing shader kinds

---

CONTRIBUTORS
libshaderc/include/shaderc.h
libshaderc/src/shaderc.cc
libshaderc/src/shaderc_test.cc

This is useful for diagnostic purposes when embedded in test apps.

Add shaderc_get_spv_version() to retrieve SPIR-V version/revision

---

libshaderc/include/shaderc.h

When built in environments with warnings enable, newer versions of
GCC complain about two of the function definitions not being prototypes. This
is solved by using (void) instead of ()

Ensure prototypes don't have empty parameter lists

---

cmake/setup_build.cmake

Otherwise, the android build will fail to
build libshaderc_combined.a

Android build needs to find 'echo' first.

---

third_party/Android.mk

OSDependent moved into Unix and Windows rather than
Linux and Windows.
It also requires that -DGLSLANG_OSINCLUDE_UNIX is specified
for Unix builds.

Fixed android ndk-build from change to paths in glslang.

---

.appveyor.yml
.travis.yml
README.md
third_party/CMakeLists.txt

We recommend something newer than googletest 1.7.0 because
we want to pick up a fix for an RTTI issue related to mocking
https://github.com/google/googletest/issues/610
That's fixed on the googletest master branch after 2015-11-10.

Use googletest master branch.

---

cmake/utils.cmake
glslc/test/CMakeLists.txt
glslc/test/glslc_test_framework.py

Those files contain tests for the test framework; they should be
added separately.

Skip scanning Python files for nose tests in glslc test framework.

---

libshaderc/src/shaderc.cc
libshaderc_util/src/compiler.cc

These were encountered when building in an environment with many warnings enabled.

Fix several compilation warnings/errors with VS2013

---

libshaderc_util/include/libshaderc_util/counting_includer.h

Reported by Clang with version number higher than 3.6.

Fix warning caused by braces around scalar initializer.

---

cmake/setup_build.cmake
cmake/utils.cmake
glslc/CMakeLists.txt
glslc/test/CMakeLists.txt
libshaderc/CMakeLists.txt
libshaderc_util/CMakeLists.txt

If a third-party project defines a CMake function with the same
name, by importing that project's CMake configuration, we may end
up overwriting our own copy. Qualify all defined functions to
reduce that probability.
Counterpart for https://github.com/KhronosGroup/SPIRV-Tools/pull/85

Qualify CMake function names with "shaderc" to avoid conflictions.

---

cmake/utils.cmake
libshaderc/CMakeLists.txt

shaderc_combined.lib will now be built and tested when compiling
for MSVC or Ninja on Windows.

Add libshaderc_combined to Windows builds.

---

third_party/CMakeLists.txt

When spirv-tools is added outside the Shaderc project, let that outside
location decide how and if to run the spirv-tools tests.

Don't run spirv-tools-testsuite.

---

libshaderc/include/shaderc.h

Instead use shaderc_module_get_status and check for return value
shaderc_compilation_status_success.
Addresses https://github.com/google/shaderc/issues/129

Remove shaderc_module_get_success

---

third_party/Android.mk

This allows both spirv-tools and glslang to live in separate source
directories when being invoked with ndk-build.
ndk-build THIRD_PARTY_PATH=foo  specifies that foo/glslang and
foo/spirv-tools exist.
ndk-build SPVTOOLS_LOCAL_PATH=/some/absolute/path specifies that glslang
exists in third_party/glslang but spirv-tools exists at
/some/absolute/path.
ndk-build GLSLANG_LOCAL_PATH=/some/absolute/path is the same but for
glslang.

Allow spirv-tools and glslang to live elsewhere.

---

third_party/Android.mk

When glslang_tab.cpp and glslang_tab.cpp.h moved, the include directory
was not updated.
This was missed because the old files had not been removed from the
source directory.

Added missing include directory to android build scripts.

---

CMakeLists.txt

The build-version target depends on glslang and spirv-tools
so we have to make sure they are included before generating the
custom target.

Fix the build-version target.

---

Android.mk
android_test/test.cpp

When we generate libshaderc_combined in Android.mk, also
create a libs/ and include/ directory that contains the actual
libraries.
This means a library can be created containing the libraries and
include files with the following style command.
ndk-build APP_PROJECT_PATH=<path/to/shaderc>
APP_BUILD_SCRIPT=<path/to/shaderc/Android.mk> APP_STL=<stl_version>
APP_ABI=<abis_to_build> NDK_APP_LIBS_OUT=<target_dir>
This will generate a target_dir with the following format
<target_dir> /
include /
shaderc /
shaderc.h
shaderc.hpp
libs /
<abis>
libshaderc.a

Export the includes in the android.mk file

---

CMakeLists.txt
cmake/setup_build.cmake
glslc/test/CMakeLists.txt
third_party/CMakeLists.txt

It looks like some verisons of cmake set PYTHON_EXE but others
do not. According to the documentation PYTHON_EXECUTABLE
is the correct way to do it.

Fixed CMake to use PYTHON_EXECUTABLE everywhere.

---

libshaderc_util/src/compiler_test.cc

On MSVC gtest copies the struct passed into a parameterized test.
It does this via assignment, so we have to make it assignable.

Fixed the windows build.

---

CMakeLists.txt
cmake/utils.cmake
libshaderc/CMakeLists.txt
libshaderc/src/shaderc_c_smoke_test.c

This C file just compiles a single shader, but is sufficient
to make sure that shaderc.h can always be included from C.

Added simple C smoke test to prevent future C breakages.

---

CMakeLists.txt
cmake/linux-mingw-toolchain.cmake
cmake/utils.cmake
libshaderc_util/CMakeLists.txt
third_party/CMakeLists.txt

Requires similar changes in Glslang and SPIRV-Tools.
Passes tests on Linux.
Compiles executables on Windows.  However, MinGW can't compile googletest, so test executables are skipped.

DO NOT MERGE: Support Linux-to-Windows cross compile via MinGW

---

README.md

A bad interaction between CMake, MinGW, and Googletest prevents
MinGW from compiling Googletest with threads.
https://github.com/google/googletest/issues/606
So we must configure Googletest without threading support.

Update README for MinGW compile

---

cmake/utils.cmake
libshaderc_util/CMakeLists.txt
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/include/libshaderc_util/mutex.h
libshaderc_util/src/counting_includer_test.cc
libshaderc_util/src/mutex_test.cc

Once support in mingw is improved, we can switch back to std::mutex.

Removed the requirement of std::mutex from shaderc.

---

third_party/Android.mk

glslang_tab.cpp is now checked into the glslang repository,
remove the requirement in Android.mk to invoke bison to generate
the file.

Remove building of glslang_tab.cpp from Android.mk

---

glslc/README.asciidoc
glslc/src/file_includer.cc
glslc/src/main.cc
glslc/test/glslc_test_framework.py
glslc/test/include.py
glslc/test/placeholder.py
libshaderc_util/include/libshaderc_util/counting_includer.h
libshaderc_util/include/libshaderc_util/file_finder.h
libshaderc_util/src/file_finder.cc

glslc will now by default try and resolve #included files relative to
the current file first, only after that fails will it try to include
files based on the -I parameters.

Enabled relative includes in glslc.

---

glslc/src/main.cc
third_party/Android.mk

Counterpart for https://github.com/KhronosGroup/SPIRV-Tools/pull/170

libspirv.h in SPIRV-Tools removed macros for version and revision.

---

third_party/Android.mk

Counterpart for https://github.com/KhronosGroup/SPIRV-Tools/pull/174.

Reflect ExtInstSet generation steps of SPIRV-Tools in Android.mk.

---

glslc/test/option_target_env.py
libshaderc_util/src/compiler_test.cc

Add unit and integration tests check that Vulkan-specific shaders
compile for the default compiler target, and when we explictly specify
the Vulkan target.
Add unit tests to check that OpenGL-specific shaders fail to compile
when targeting Vulkan.

Test Vulkan-specific shaders

---

Android.mk
glslc/CMakeLists.txt
libshaderc_util/CMakeLists.txt
third_party/Android.mk

This commit requires a matching update to
github.com/google/glslang to catch up to
github.com/KhronosGroup/glslang.
Also remove include directories for SPIRV-Tools that no
longer exist.

Support Glslang with its new HLSL parser library

---

libshaderc_util/src/compiler_test.cc

Glslang bug 229 has been fixed.

Enable test for failure of Vulkan shader targeting OpenGL

---

Android.mk

Missing , in $(call host-cp) merged arguments on windows into broken
path.
cd - does not work on windows, replace with cd $(ROOT_SHADERC_PATH)

Fixed Android.mk for Windows.

---

cmake/utils.cmake

This avoids needing to ship libgcc_s_sjlj-1.dll with your
executable.
The rule still applies to C++ executables.

MinGW linking C executables: statically link libgcc

---

third_party/Android.mk

Fixes building for Android using updated Glslang sources.
Requires a that we update google/glslang

Gsllang has a new source file.

---

.appveyor.yml
.travis.yml
README.md

Counterpart of https://github.com/KhronosGroup/SPIRV-Tools/pull/186.

SPIRV-Tools now requires SPIRV-Headers.

---

third_party/Android.mk

The locations of the headers and grammar files have
moved.  Also the names of the grammar files have changed.

Android: Use grammar files from SPIRV-Headers repo

---

libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/src/compiler.cc

Glslang's builtin function table cache is now sensitive
to the Spv vs. non-Spv and Vulkan vs. GL.
That is https://github.com/KhronosGroup/glslang/issues/166 is fixed.
So now we don't have to tear down Glslang's internal state when
the "message rules" change. That's how Vulkan vs. GL is encoded.

Changing Vulkan vs. GL doesn't force teardown of glslang

---

glslc/test/assembly.py
glslc/test/option_dash_E.py
glslc/test/option_std.py
glslc/test/option_target_env.py
libshaderc/src/common_shaders_for_test.h
libshaderc/src/shaderc.cc
libshaderc/src/shaderc_cpp_test.cc
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/src/compiler_test.cc

* Desktop shaders compiling to SPIR-V require version 330 or higher.
* A new control for reporting cascading errors is introduced. (We'd better turn off cascading errors, but that can happen in another PR.)

Fix tests for catching up with upstream glslang

---

Dockerfile

Also use this to trigger a rebuild on bots.

Update Dockerfile to pull SPIRV-Headers before building.

---

third_party/Android.mk

SPIRV-Tools source file list has changed.

Build SPIRV-Tools file Instruction.cpp instead of Id.cpp

---

CHANGES
CMakeLists.txt
cmake/setup_build.cmake
glslc/test/CMakeLists.txt
third_party/CMakeLists.txt

Previously, the build was invoking python via the undefined
variable PYTHON_EXECUTABLE.
Fixes https://github.com/google/shaderc/issues/238

Invoke python via PYTHON_EXE discovered by cmake

---

third_party/Android.mk

This is required to absorb the recent merge of the overloaded-400
branch into Glslang master.
See
https://github.com/KhronosGroup/glslang/commit/ab89bbe702e88c01c2522155c54fc722161276db

Update Glslang sources for Android NDK build

---

glslc/test/messages_tests.py

Change "main function" to "entry point".
This is required to update to latest Glslang sources:
https://github.com/KhronosGroup/glslang/commit/6fccb3cd75cdc34b63461dff19a1d2bd0ef9159f

Update glslang error messages about entry points

---

third_party/Android.mk

Requires to update https://github.com/google/glslang to 7f7c2ed7809b0041f508e4d99dbf2c1284d0c320

Add new file appeared in glslang.

---

libshaderc/include/shaderc/shaderc.h
libshaderc/include/shaderc/shaderc.hpp
libshaderc/src/shaderc.cc
libshaderc/src/shaderc_cpp_test.cc
libshaderc/src/shaderc_test.cc
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/include/libshaderc_util/spirv_tools_wrapper.h
libshaderc_util/src/compiler.cc
libshaderc_util/src/compiler_test.cc
libshaderc_util/src/spirv_tools_wrapper.cc

Address #251.
* Chanage the C interface for assembling to accept options.
Also together with the C interface change, new overloads for assembling
are added into the C++ interface.
* Sort out target environments used in different components.
SPIRV-Tools has its own target environment definition, and public
shaderc API has its own. A new one is added into `Compiler` in
`shaderc_util`, for better isolation.
Now `shaderc_util::Compiler`'s interface accepts target environment,
not glslang messages anymore. All the conversion to glslang messages
are done in the implementation now.

Plumb target environment to SPIRV-Tools

---

libshaderc_util/CMakeLists.txt
libshaderc_util/src/file_finder_test.cc

This allows us run a test exectuable against a different
copy of the source tree.
Facilitates testing of MinGW-built executables on Windows.

Make tests detect working directory at runtime

---

third_party/Android.mk

On windows, abspath will mangle a path that is already absolute instead
of leaving it alone. Use the functions built into the NDK to
only create an absolute path if it is not already absolute.

Work around bug with abspath on windows.

---

third_party/Android.mk

Match upstream behaviour.
(FIxes Android.mk builds, until https://github.com/KhronosGroup/glslang/pull/556 goes in)

Enable AMD extensions for Glslang by default.

---

libshaderc/include/shaderc/shaderc.h
libshaderc/include/shaderc/shaderc.hpp
libshaderc/src/common_shaders_for_test.h
libshaderc/src/shaderc.cc
libshaderc/src/shaderc_cpp_test.cc
libshaderc/src/shaderc_test.cc
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/src/compiler.cc
libshaderc_util/src/compiler_test.cc

Exposes the HLSL functionality in Glslang.
Done in three layers:
- libshaderc_util::Compiler:
Add libshaderc_util::Compiler::SourceLanguage enum.
Add libshaderc_util::Compiler::SetSourceLanguage method.
The default language remains GLSL.
libshaderc_util::Compiler passes the source language option into Glslang.
- C API
Add function to set source language on compiler options.
- C++ API
Add shaderc::CompileOptions::SetSourceLanguage

Add API support for compiling HLSL

---

third_party/Android.mk

Goes with https://github.com/KhronosGroup/SPIRV-Tools/pull/453

Removed SPIRV-Tools source/instruction.cpp

---

libshaderc/CMakeLists.txt
libshaderc/include/shaderc/shaderc.hpp
libshaderc/src/shaderc.cc
libshaderc/src/shaderc_cpp_test.cc
libshaderc/src/shaderc_test.cc
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/src/compiler.cc
libshaderc_util/src/compiler_test.cc

Before, the C API ignored the entry point name.
Before, the C++ API didn't have entry points that accepted
an entry point name.

C, C++ APIs are sensitive to entry_point_name

---

glslc/test/option_dash_x.py
glslc/test/option_fentry_point.py
glslc/test/option_shader_stage.py
glslc/test/option_std.py

Glslang now warns when an HLSL shader entry point can't
be found that either matches the default of "main" or
one specified via -fentry-point.

Update tests for more strict glslango

---

glslc/test/assembly.py
glslc/test/expect.py
glslc/test/option_dash_cap_O.py
libshaderc/src/common_shaders_for_test.h
libshaderc_util/src/compiler.cc
libshaderc_util/src/compiler_test.cc

It's the top 16 bits of the generator word.
Test output expects a relatively recent versions of:
- SPIRV-Tools: parses tools identities from the SPIR-V XML Registry file
- SPIRV-Headers: defines the "Google over Shaderc" generator as tool #13

Set the tool to Google Shaderc over Glslang

---

glslc/test/include.py
glslc/test/line.py
glslc/test/option_dash_M.py

Also the #include directive now requires a newline at the end.
That is a requirement from C++.
This is required so we can refresh google/shaderc from upstream

Adapt to Glslang include message changes

---

utils/update_build_version.py

This enables the case where the source code is checked
out with DOS line endings on a Linux system.  There will
be a trailing carriage return before Python sees the line
ending.

Allow trailing whitespace in version lines in CHANGES

---

cmake/setup_build.cmake

Small change to fix how we are configured if included by Android Studio.
The main difference between Android Studio CMake, and
android-cmake, at least as far as this is concerned is that Android
Studio does not define find_host*. In this case we can just use
find_package and find_program, so set up the macros in that way.

Updated CMake configuration for Android Studio.

---

libshaderc/src/shaderc.cc
libshaderc_util/include/libshaderc_util/counting_includer.h
libshaderc_util/src/compiler_test.cc
libshaderc_util/src/counting_includer_test.cc

See Glslang test https://github.com/KhronosGroup/glslang/pull/663
All Shaderc tests pass with this change and the Glslang change.

Adapt to Glslang Includer interface changes.

---

examples/online-compile/main.cc
libshaderc/include/shaderc/shaderc.h

Fixes:
- Fix the shader source to be valid
- Add an entry point name argument
- Add an options object
Updated the online compilation example with a simple use of the C API.

Fix shaderc_compile_to_spv examples in shaderc.h

---

third_party/Android.mk

Before the first build, the Android.mk build system can't see
for itself the transitive dependency via
table.h -> extensions.h -> extension_enum.inc.
Since table.h is so fundamental, make all (non-test) .cpp files
depend on extension_enum.inc.

Add pervasive dependency to extension_enum.inc

---

update_shaderc_sources.py

When a subprocess failed in update_shaderc_sources.py, it was impossible
to know the failure's reason without hacking the script, because the
script suppressed the stderr of all subprocesses.
For example, when `git fetch` failed on the shaderc repo, the script
printed only this error message:
Failed to run ['git', 'fetch', 'known-good'] in .
Is there no network connection? Did ssh authentication fail? Is the
repository corrupt? Who knows what happened?!?!?! Answer: stderr knows
what happened.

Don't suppress stderr of subprocesses

---

third_party/Android.mk

This goes with https://github.com/KhronosGroup/SPIRV-Tools/pull/595
to support SPV_AMD_gcn_shader

Support non-standard vendor extended instructions

---

glslc/test/line.py
glslc/test/option_target_env.py

An extra space now appears at the front of the type listed
in an invalid conversion error message.

Update tests for Glslang message changes

---

glslc/test/option_dash_x.py

This is necessary before we can refresh google/glslang from upstream

Update tests for different Glslang error message

---

glslc/test/include.py
glslc/test/messages_tests.py
glslc/test/option_dash_M.py
glslc/test/option_target_env.py
libshaderc/src/common_shaders_for_test.h
libshaderc/src/shaderc_cpp_test.cc
libshaderc/src/shaderc_test.cc
third_party/Android.mk
third_party/CMakeLists.txt
utils/copy-tests-if-necessary.py

- glslang added an #include facility; adjust test copying to accomodate
- glslang requires location annotation on shader inputs and outputs
- glslang global warnings changed; use forced version/profile instead of unknown version
- glslang removed two .cpp files with empty contents (Affects Android.mk)
- SPIRV-Tools added two new optimization passes. (Affects Android.mk)
These changes are required to be able to refresh google/glslang

React to Glslang and SPIRV-Tools changes

---

glslc/test/parameter_tests.py
libshaderc_util/src/resources.cc

Glslang has default of 32.
Vulkan driver on Pixel in Android N has maxFragmentOutputAttachments of 8.

Increase default maxDrawBuffers

---

glslc/test/option_std.py
libshaderc/src/shaderc_cpp_test.cc
libshaderc/src/shaderc_test.cc

- Glslang issues an error for unknown version or profile
- Glslang supports 320es, so that changes one error message.

Adapt to Glslang error changes

---

cmake/utils.cmake

Some asciidoctor installations are broken in a mysterious way. HTML
documentation generation is not critical, so don't force the default
build target to depend on it.
Fixes https://github.com/google/shaderc/issues/363

Don't build HTML docs by default

---

CHANGES
cmake/utils.cmake
libshaderc/CMakeLists.txt
libshaderc/include/shaderc/shaderc.h

PR for a CQ dry-run. Heavily based off #342

Add shared library variant for libshaderc

---

.appveyor.yml
README.md

This pull request added configuration for uploading Appveyor
build artifacts of master top of the tree to the GitHub
"Releases" page. The following are published:
* glslc.exe
* shaderc headers
* shaderc_combined.lib
* shaderc_shared.dll

Deploy Appveyor build artifacts to GitHub Releases

---

libshaderc/include/shaderc/shaderc.h

_WIN32 is defined by MSVC compilers on Windows platform, not
WIN32.
See https://msdn.microsoft.com/en-us/library/b0084kay.aspx
Addresses https://github.com/google/shaderc/issues/383

Check _WIN32 instead of WIN32 for building shared library

---

.appveyor.yml
.gitignore
.travis.yml
README.md
third_party/CMakeLists.txt

This makes the directory hierarchy less complicated.

Allow SPIRV-Headers to be checked out at third_party/

---

glslc/test/assembly.py
glslc/test/expect.py
glslc/test/option_dash_cap_O.py
libshaderc/src/common_shaders_for_test.h

The lower 16bits of the generator number is now 2, up from 1.
See Glslang commit.
https://github.com/KhronosGroup/glslang/commit/07ed11f9a08820505eef1e128bd758b8b9b5ed5b
Glslang updated its generator version number to highlight
a behaviour fix related to atomic decrement, in commit
https://github.com/KhronosGroup/glslang/commit/48d6e798bc76b8e58be844a8cef8bc6f843a909e
(Requires a correponding refresh of google/glslang from KhronosGroup/glslang)

Adapt to Glslang generator version number change

---

cmake/utils.cmake

Android NDK build uses a MinGW build that warns if -fPIC is specified
because PIC is always turned on anyway.  That causes an error since
we have warnings as errors.

Avoid -fPIC for MinGW builds

---

glslc/test/expect.py

Some Glslang versions emit a version word of 0 for opengl_compat
profile.

glslc tests: Relax version word check

---

glslc/test/assembly.py
glslc/test/expect.py
glslc/test/option_dash_cap_O.py
libshaderc/src/common_shaders_for_test.h

Glslang codegen updates to 3, for memory barrier semantics changes.
This is required to refresh google/glslang from upstream KhronosGroup/glslang

Adapt to Glslang codegen version update

---

glslc/test/option_fauto_bind_uniforms.py
glslc/test/option_fresource_set_binding.py
libshaderc/src/common_shaders_for_test.h

A test shader should use the resources or samplers whose
bindings are being checked.

Make tests resilient to better SPIR-V optimizations

---

CHANGES
glslc/test/option_fauto_bind_uniforms.py
glslc/test/option_flimit.py
libshaderc/src/shaderc_cpp_test.cc
libshaderc/src/shaderc_test.cc
libshaderc_util/src/compiler_test.cc

Either supply a binding via layout annotation in the shader,
or use the auto-map-uniforms option.
This goes along with a refresh of google/glslang from upstream.  Bots will fail on this PR since they won't pick up the Glslang changes in https://github.com/KhronosGroup/glslang/pull/1256

Glslang now requires bindings on resources

---

.appveyor.yml

Upstream googletest has fixed its
https://github.com/google/googletest/issues/1268
so it no longer "pollutes" the cmake environment of surrounding
projects (like Shaderc) to add that extra "d".

AppVeyor packaging: debug DLL name no longer has extra "d"

---

.appveyor.yml

This makes it KISS.
Why indirect through an environment variable name when you can easily misspell the environment variable name?

Fix setting of debug DLL name for AppVeyor

---

glslc/test/assembly.py
glslc/test/expect.py
glslc/test/option_dash_cap_O.py
libshaderc/src/common_shaders_for_test.h

Reverses previous change.
React to today's update to Glslang.
https://github.com/KhronosGroup/glslang/commit/ac3707921ed313eaba1c206e8113b85fef054c34
This is required to update google/glslang

Glslang generator version 6

---

glslc/README.asciidoc
glslc/src/main.cc
glslc/test/expect.py
glslc/test/option_target_env.py
glslc/test/parameter_tests.py
libshaderc/include/shaderc/shaderc.h
libshaderc/include/shaderc/shaderc.hpp
libshaderc/src/common_shaders_for_test.h
libshaderc/src/shaderc.cc
libshaderc/src/shaderc_cpp_test.cc
libshaderc/src/shaderc_test.cc
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/src/compiler.cc
libshaderc_util/src/compiler_test.cc

NOTE: We no longer can compile OpenGL compatibility profile shaders to SPIR-V.
These will error out.
C and C++ API: Set nontrivial target environment version
Glslc --target-env accepts optional version suffix, e.g. vulkan1.1

Support setting target environment version, e.g. Vulkan 1.1

---

glslc/README.asciidoc
glslc/src/main.cc
glslc/test/option_dash_cap_O.py
libshaderc/include/shaderc/shaderc.h
libshaderc/src/common_shaders_for_test.h
libshaderc/src/shaderc.cc
libshaderc/src/shaderc_cpp_test.cc
libshaderc/src/shaderc_test.cc
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/include/libshaderc_util/spirv_tools_wrapper.h
libshaderc_util/src/compiler.cc
libshaderc_util/src/spirv_tools_wrapper.cc
third_party/CMakeLists.txt

Previously we manually manage the list of passes.
This commit converts to use the SPIRV-Tools standard
ones.

Use standard SPIRV-Tools transformation recipes

---

glslc/src/file_compiler.cc
glslc/test/expect.py
glslc/test/option_dash_o.py
libshaderc_util/include/libshaderc_util/io.h
libshaderc_util/src/io.cc

For the test: also refactor the glslc test expectation code to
be able to check the length and header of a binary residing in a
Python "bytes" object, not just in a file.
Fixes https://github.com/google/shaderc/issues/457

Force binary mode when writing a binary to stdout

---

BUILD.gn
build_overrides/shaderc.gni

This CL adds the necessary build configuration to allow building
shaderc within a Chromium checkout.

Add BUILD.gn rules.

---

BUILD.gn

PTAL @dj2 @dneto0 this should be the last one of these PRs for now (at least to roll into Dawn, Chrome might need more)

BUILD.gn: Avoid source_set depending on static_libraries

---

libshaderc/src/common_shaders_for_test.h
libshaderc/src/shaderc_test.cc
libshaderc_util/src/spirv_tools_wrapper.cc

These two validation exceptions are needed for HLSL compilation.
Fixes https://github.com/google/shaderc/issues/499

Disable layout and relax logical pointer for optimizer validation

---

BUILD.gn

This had no sources and depended on a source_set which is an invalid use
of GN because the source_set gets propagated to dependents of the
static_library instead.
PTAL @dneto0 !

BUILD.gn: remove the static_library target.

---

.gitignore
README.md
kokoro/android-release/build.sh
kokoro/linux/build.sh
kokoro/macos/build.sh
kokoro/ndk-build/build.sh
kokoro/windows/build.bat
third_party/CMakeLists.txt

The effcee library was made a requirement for building the SPIRV-Tools test suite. When building that suite through shaderc we need to make sure the required dependencies are available.

Add effcee and re2 when building spirv-tools tests

---

libshaderc_util/src/shader_stage.cc

This adds missing support for raytracing and task/mesh shaders to
shader_stage() pragma so that you can build these shaders without
specifying the stage via command line arguments.

Add support for NV_EXTENSIONS in #pragma shader_stage()

---

Dockerfile

Currently, building the docker container fails with:
```
CMake Error at third_party/CMakeLists.txt:49 (add_subdirectory):
add_subdirectory given source "/root/shaderc/third_party/re2" which is not
an existing directory.
CMake Error at third_party/CMakeLists.txt:50 (add_subdirectory):
add_subdirectory given source "/root/shaderc/third_party/effcee" which is
not an existing directory.
```
It looks like the CMake file has been changed without updating the Dockerfile. This just adds a git clone of the two projects.

Add git clone of re2 and effcee to the Dockerfile

---

kokoro/android-release/build.sh

Update the kokoro Android build with a newer NDK.
This will be needed when we incorporate spirv-cross into shaderc.
Also remove re2 and effcee from the script as they were not used.

Update Android NDK.

---

glslc/test/option_dash_cap_O.py
libshaderc/src/common_shaders_for_test.h
libshaderc/src/shaderc_cpp_test.cc
libshaderc/src/shaderc_test.cc
libshaderc_util/src/compiler.cc

Pass the necessary flags through to glslang to get it to emit OpSource containing the shader source text if it was requested in the options.
Implements issue #455.

Generate source text debug info if requested

---

DEPS
glslc/test/option_dash_cap_O.py

This CL rolls GLSLang and reverts the test change made to make MacOS pass as it has
now been fixed upstream in GLSLang.

Fixup source matching test

---

third_party/Android.mk

This fixes building with ndk-build when the source tree is laid
out like in the Android NDK.

Android.mk: better fallback for SPIRV-Tools dir

---

README.md
android_test/jni/Application.mk
kokoro/ndk-build/build.sh
kokoro/ndk-build/presubmit_khronos.cfg

Update the build script in kokoro/ndk-build so it works again.

Fix NDK build.

---

BUILD.gn

Components are a concept defined in Chromium's BUILDCONFIG.gn that are
shared libraries (with the right rpath set up) or static_libraries
depending on whether is_component_build is defined.
This changes libshaderc and libshaderc_spvc to be components mostly so
that the right rpath options are set up automatically when they are
shared libraries.
Also fixes missing shaderc_util_public in the public_configs of both
libraries.

BUILD.gn: Make libraries Chromium-style "components"

---

BUILD.gn

We need the dependency "spirv_cross_full_for_fuzzers" which represents
all of spirv-cross.  The dependency "spirv_cross" can omit parts of
spirv-cross.  This should fix the chrome build.

Use the full spirv-cross dependency.

---

BUILD.gn
DEPS
libshaderc_spvc/include/shaderc/spvc.h
libshaderc_spvc/include/shaderc/spvc.hpp
libshaderc_spvc/src/spvc.cc
libshaderc_spvc/src/spvc_c_smoke_test.c
libshaderc_spvc/src/spvc_cpp_test.cc
libshaderc_spvc/src/spvc_test.cc

Add enough functions to libshaderc_spvc so it can be used by Dawn fuzzers.

Flesh out for Dawn fuzzers.

---

DEPS
glslc/src/resource_parse_test.cc
libshaderc/src/shaderc_cpp_test.cc
libshaderc/src/shaderc_test.cc
libshaderc_util/src/compiler_test.cc
libshaderc_util/src/version_profile_test.cc

INSTANTIATE_TEST_CASE_P has been deprecated. We need to use
INSTANTIATE_TEST_SUITE_P instead.

Remove use of deprecated googletest macro

---

CMakeLists.txt
libshaderc_spvc/CMakeLists.txt

Fix faulty and confusing logic for enabling/disabling libshaderc_spvc.
Add a couple missing spirv-cross lib dependencies.

Fix cmake build for libshaderc_spvc.

---

glslc/src/resource_parse_test.cc
libshaderc_util/src/version_profile_test.cc

This is required to compile against latest googletest.

Remove commas for googltest test suite macro

---

kokoro/ndk-build/build.sh
third_party/Android.mk

We need this until the NDK build has the SPIRV-Cross source.

spvc is optional, off by default, in Android.mk

---

cmake/utils.cmake

Including shaderc in project that declares multiple build configurations
and then using generator that doesn't support multi-configuration would
result in a target path with a leading dot slash.  Ninja doesn't work
in that case.
Prepend CMAKE_CURRENT_BINARY_DIR in order to get an absolute path and
make ninja happy.  This works in all cases so we remove code specific
to multi-configuration.
Fixes #568.

Avoid leading dot slash in cmake target.

---

DEPS
spvc/src/main.cc
spvc/test/run_spirv_cross_tests.py

Update DEPS to work with spirv-cross tests.
Fix spvc return status.
Simplified the test script:
- no caching of compiled shaders
- all testing steps in one place
- removed unsupported spvc flags
Also clean up temporary files so they can't mess with subsequent testing.

Enable spvc test.

---

libshaderc_spvc/include/shaderc/spvc.h
libshaderc_spvc/include/shaderc/spvc.hpp
libshaderc_spvc/src/spvc.cc
spvc/src/main.cc
spvc/test/run_spirv_cross_tests.py

This builds on https://github.com/google/shaderc/pull/578
spvc: Add some flags.
Implement the following spvc flags and update the test:
--entry
--version
--remove-unused-variables
--vulkan-semantics
--separate-shader-objects
--flatten-ubo
The old --version flag is now -v.

spvc: Add some flags.

---

spvc/test/run_spirv_cross_tests.py

Add some flags to the spvc test script to aid development:
--log for logging all commands executed,
--dry-run to not execute commands,
--give-up to exit after first failure.
One use of the log is to compare behavior to the SPIRV-Cross test,
so we log what SPIRV-Cross would do, even commands we don't need to do.

spvc testing: add logging.

---

DEPS
spvc/test/run_spirv_cross_tests.py

Pick up a fix to SPIRV-Tools that will let us add more spvc tests without
blowing up in debug builds.
The SPIRV-Tools roll itself broke some SPIRV-Cross tests, so we also
have to roll in a new SPIRV-Cross that works with the new SPIRV-Tools.
Update glslang and SPIRV-Headers to stay in sync with the new SPIRV-Cross.

Roll DEPS.

---

CMakeLists.txt
cmake/shaderc.pc.in
cmake/shaderc_combined.pc.in
cmake/shaderc_static.pc.in
cmake/write_pkg_config.cmake

Extracts the current version from the file CHANGES
The -dev suffix maps to a minor version number of .0
No -dev suffix maps to a minor version number of .1
Uses a first class target spirv-tools-pkg-config
Stolen from SPIRV-Tools.

Export config files for pkg-config.  (#392)

---

CMakeLists.txt
README.md
cmake/setup_build.cmake
glslc/test/CMakeLists.txt
spvc/test/CMakeLists.txt

Tests for glslc and SPIRV-Tools require either Python3 or Python2
with the "future" package.  But since we can't rely on developers
having the "future" package, migrate fully to Python3 now.

Shaderc requires Python3

---

README.md
downloads.md
kokoro/linux/build.sh
kokoro/linux/continuous_clang_debug.cfg
kokoro/linux/continuous_clang_release.cfg
kokoro/linux/continuous_gcc_debug.cfg
kokoro/linux/continuous_gcc_release.cfg
kokoro/macos/build.sh
kokoro/macos/continuous_clang_debug.cfg
kokoro/macos/continuous_clang_release.cfg
kokoro/windows/build.bat
kokoro/windows/continuous_debug_2017.cfg
kokoro/windows/continuous_release_2013.cfg
kokoro/windows/continuous_release_2015.cfg
kokoro/windows/continuous_release_2017.cfg

Add a step at the end of each build to install then package the
installation directory.
Name the package in the config of each build we want to upload.
Add a page that points to all the latest builds which can be downloaded.

Package and upload builds.

---

kokoro/linux/build.sh
kokoro/macos/build.sh
kokoro/windows/build.bat

The Windows package was not being put in the same place as the others
and was not being found by the uploader.  This makes the build scripts
more consistent with each other and lets the Windows upload work.

Fix Windows build uploads.

---

glslc/test/option_fhlsl_functionality1.py
libshaderc/src/shaderc_cpp_test.cc
libshaderc/src/shaderc_test.cc
libshaderc_util/src/compiler_test.cc

This is required for SPIR-V 1.4 support

1.4: GOOGLE suffix drops from certain instructions

---

spvc/test/run_spirv_cross_tests.py

Use explicit list comprehension to map the command elements to strings.
Otherwise I get a "map object is not indexible" error when evaluating
cmd[0] two lines later.

Fix spvc test logging

---

spvc/test/run_spirv_cross_tests.py

By default, SPIRV-Tools will assemble for the latest supported
version of SPIR-V.  With SPIR-V 1.4 arriving, that will generally
make modules which are not consumable by Vuklan 1.1.  So update
the Spvc tests to explicitly assemble for Vulkan 1.1.

Spvc tests: Assemble explicitly for Vulkan1.1 env

---

libshaderc_spvc/include/shaderc/spvc.h
libshaderc_spvc/include/shaderc/spvc.hpp
libshaderc_spvc/src/spvc.cc
spvc/README.asciidoc
spvc/src/main.cc

Clarify that the environment being referenced is the one associated
with the provided SPIR-V, and not the produced artifact.
Fixes #609

Change 'target' env to 'source' env in spvc API

---

utils/git-sync-deps

Getting uniformity across different projects that use Python3 and
git-sync-deps.
Fixes #635

Ran 2to3 on git-sync-deps

---

DEPS
utils/git-sync-deps

This is the format that glcient, which is used by Autoroller
expects. Adding to git-sync-deps translating for internal
processing.
Fixes #662

Convert vars['foo'] to Var('foo')

---

libshaderc/CMakeLists.txt
libshaderc_spvc/CMakeLists.txt

A slight bug occurs when running a cmake install on shaderc when using Visual Studio as a generator, where the source install file paths are incorrect. They contain a duplicate absolute path.
This issue occurred when a pull request was merged in order to fix the Ninja build system back in this PR https://github.com/google/shaderc/pull/570
The issue is fixed by relying on the shaderc_combine_static_lib() function to properly set an absolute path on the location of the shaderc_combined custom target.
You can verify that this install behavior now works properly by running this on a Windows machine, generating for VS2017:
```
git clone https://github.com/RikoOphorst/shaderc
cd shaderc
mkdir build
cd build
cmake ../ -G"Visual Studio 15 2017 Win64"
cmake --build . --target install
```
Apologies …

Fixing duplicate absolute install paths when using Visual Studio generators

---

libshaderc_spvc/include/shaderc/spvc.h
libshaderc_spvc/include/shaderc/spvc.hpp
libshaderc_spvc/src/spvc.cc

This method needs to live a little longer to allow downstream users to
migrate without causing build breakages.
This is part of #673

Re-introduce SetShaderModel for backwards compatibility

---

DEPS

https://github.com/google/effcee.git
/compare/8f0a61dc95e0..b83b58d177b7
git log 8f0a61dc95e0df18c18e0ac56d83b3fa9d2fe90b..b83b58d177b797edd1f94c5f10837f2cc2863f0a --date=short --no-merges --format=%ad %ae %s
2019-01-29 stevenperron@google.com Update tests to work with the latest googletest.
2019-01-14 dneto@google.com Fix effcee-example MinGW cross-compile
The AutoRoll server is located here: https://autoroll.skia.org/r/effcee-shaderc-autoroll
If the roll is causing failures, please contact the current sheriff (rmistry@google.com), and stop

Roll third_party/effcee 8f0a61dc95e0..b83b58d177b7 (2 commits)

---

DEPS

https://github.com/KhronosGroup/SPIRV-Headers.git
/compare/9242862c84fe..9cf7c3a7d2d2
git log 9242862c84fe295ca0c9d26b36a6a891bb3ed6a7..9cf7c3a7d2d203b1ee35896547b9644e28d9280e --date=short --no-merges --format=%ad %ae %s
2019-06-10 ehsannas@gmail.com Add grammar and symbols for UserTypeGOOGLE extension to unified1.
The AutoRoll server is located here: https://autoroll.skia.org/r/spirv-headers-shaderc-autoroll

Roll third_party/spirv-headers 9242862c84fe..9cf7c3a7d2d2 (1 commits)

---

DEPS

https://github.com/KhronosGroup/SPIRV-Cross.git
/compare/5e9e8918f9a2..fccf1d046204
git log 5e9e8918f9a22d488811c575a97ccda2d8a8726d..fccf1d046204802aa04f05b4af7ca91fab37c50f --date=short --no-merges --format=%ad %ae %s
2019-06-12 post@arntzen-software.no Add MSL 2.2 path in test_shaders.py.
The AutoRoll server is located here: https://autoroll.skia.org/r/spirv-cross-shaderc-autoroll

Roll third_party/spirv-cross 5e9e8918f9a2..fccf1d046204 (1 commits)

---

DEPS

https://github.com/KhronosGroup/SPIRV-Cross.git
/compare/fccf1d046204..00a8539d1ddf
git log fccf1d046204802aa04f05b4af7ca91fab37c50f..00a8539d1ddf8d0d934813e409500af6363c96f1 --date=short --no-merges --format=%ad %ae %s
2019-06-11 post@arntzen-software.no MSL: Support Invariant qualifier on position.
The AutoRoll server is located here: https://autoroll.skia.org/r/spirv-cross-shaderc-autoroll

Roll third_party/spirv-cross fccf1d046204..00a8539d1ddf (1 commits)

---

DEPS

/compare/076b7f778883..89656ddbe62f
git log 076b7f7788833ca31206bc30e5a2cfbdb9628f29..89656ddbe62f9f0eeb6447868b31f2ec3b1052bb --date=short --no-merges --format=%ad %ae %s
2019-06-12 gennadiycivil@users.noreply.github.com Update README.md

Roll third_party/googletest 076b7f778883..89656ddbe62f (1 commits)

---

DEPS

https://github.com/KhronosGroup/SPIRV-Headers.git
/compare/9cf7c3a7d2d2..de99d4d834ae
git log 9cf7c3a7d2d203b1ee35896547b9644e28d9280e..de99d4d834aeb51dd9f099baa285bd44fd04bb3d --date=short --no-merges --format=%ad %ae %s
2019-06-12 dneto@google.com Add Volatile to Memory Semantics, for SPV_KHR_vulkan_memory_model
The AutoRoll server is located here: https://autoroll.skia.org/r/spirv-headers-shaderc-autoroll

Roll third_party/spirv-headers 9cf7c3a7d2d2..de99d4d834ae (1 commits)

---

DEPS

/compare/89656ddbe62f..af4c2cb098a3
git log 89656ddbe62f9f0eeb6447868b31f2ec3b1052bb..af4c2cb098a35f4898c5089335c10ba4bd5a4fce --date=short --no-merges --format=%ad %ae %s
2019-06-12 misterg@google.com Formatting Changes
2019-06-12 misterg@google.com Formatting Changes, README

Roll third_party/googletest 89656ddbe62f..af4c2cb098a3 (2 commits)

---

glslc/src/main.cc
libshaderc/include/shaderc/shaderc.h
libshaderc/include/shaderc/shaderc.hpp
libshaderc/src/shaderc.cc
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/src/compiler.cc

Option invert-y for compiler is simple way for using DirectX shader code for Vulkan which uses a different coordinate system. Without the need to do it manually: ```gl_Position.y = -gl_Position.y``` or use [VK_KHR_MAINTENANCE1](https://www.saschawillems.de/blog/2019/03/29/flipping-the-vulkan-viewport/) extension.

Add invert-y option for glslc and libshaderc.

---

glslc/test/parameter_tests.py

This is needed to make tests pass again.  Oops.

Update glslc tests for -finvert-y option

---

DEPS

/compare/af4c2cb098a3..26afdba792e5
git log af4c2cb098a35f4898c5089335c10ba4bd5a4fce..26afdba792e52cac00ce11644c3c0b1789c40bf7 --date=short --no-merges --format=%ad %ae %s
2019-06-12 matthias@matthiaswalter.org Setting CMP0054 policy to NEW. This allows to use the string &#34;SHARED&#34; without interpreting it as a variable.

Roll third_party/googletest af4c2cb098a3..26afdba792e5 (1 commits)

---

DEPS

https://github.com/KhronosGroup/SPIRV-Cross.git
/compare/00a8539d1ddf..4104e363005a
git log 00a8539d1ddf8d0d934813e409500af6363c96f1..4104e363005a079acc215f0920743a8affb31278 --date=short --no-merges --format=%ad %ae %s
2019-06-13 post@arntzen-software.no MSL: Fix regression with Private parameter declaration.
2019-06-12 post@arntzen-software.no MSL: Support stencil export.
2019-06-12 post@arntzen-software.no GLSL: Support GL_ARB_shader_stencil_export.
The AutoRoll server is located here: https://autoroll.skia.org/r/spirv-cross-shaderc-autoroll
the roller if …

Roll third_party/spirv-cross 00a8539d1ddf..4104e363005a (3 commits)

---

DEPS

/compare/26afdba792e5..f7c178ecb33c
git log 26afdba792e52cac00ce11644c3c0b1789c40bf7..f7c178ecb33c92763fa41d4999db30aaf43a6b30 --date=short --no-merges --format=%ad %ae %s
2019-06-13 misterg@google.com Makefiles are no longer supported. Adding pseudo-break with their impending removal to make sure that people who are interested will notice
2019-06-13 TLachecki@serif.com Fixed issue #2284 (Incompatibility with C&#43;&#43;17)
the …

Roll third_party/googletest 26afdba792e5..f7c178ecb33c (2 commits)

---

DEPS

/compare/f7c178ecb33c..e110929a7b49
git log f7c178ecb33c92763fa41d4999db30aaf43a6b30..e110929a7b496714c1f6f6be2edcf494a18e5676 --date=short --no-merges --format=%ad %ae %s
2019-06-14 misterg@google.com Documentation sync working on the documentation being included with the code
2019-06-14 misterg@google.com googlemock/docs/CookBook.md small doc test

Roll third_party/googletest f7c178ecb33c..e110929a7b49 (2 commits)

---

DEPS

https://github.com/google/re2.git
/compare/0c95bcce2f1f..848dfb7e1d7b
git log 0c95bcce2f1f0f071a786ca2c42384b211b8caba..848dfb7e1d7ba641d598cb66f81590f3999a555a --date=short --no-merges --format=%ad %ae %s
2019-06-13 junyer@google.com Don&#39;t let DFA execution bail when slow for RE2::Set.
2019-06-13 junyer@google.com Expose FilteredRE2::GetRE2() as public.
The AutoRoll server is located here: https://autoroll.skia.org/r/re2-shaderc-autoroll

Roll third_party/re2 0c95bcce2f1f..848dfb7e1d7b (2 commits)

---

DEPS

/compare/e110929a7b49..fd20d1eccef6
git log e110929a7b496714c1f6f6be2edcf494a18e5676..fd20d1eccef66e0027450f73b729c49453101b89 --date=short --no-merges --format=%ad %ae %s
2019-06-13 misterg@google.com doc is still valid
2019-06-13 misterg@google.com Finish removing autotools
2019-06-13 misterg@google.com Finish removing autotools
2019-06-13 misterg@google.com Also remove googlemock/scripts/gmock-config.in
2019-06-13 misterg@google.com Removing make and automake. The only supported build systems are Bazel internally and CMake community supported
If …

Roll third_party/googletest e110929a7b49..fd20d1eccef6 (5 commits)

---

DEPS

/compare/fd20d1eccef6..176eccfb8f42
git log fd20d1eccef66e0027450f73b729c49453101b89..176eccfb8f42339b8ea2341e926f6835f7932bc4 --date=short --no-merges --format=%ad %ae %s
2019-06-16 opensource@ioxp.de docs/primer: Fixed usage of test case

Roll third_party/googletest fd20d1eccef6..176eccfb8f42 (1 commits)

---

DEPS

One of the glslang tests is failing on the roll, but it needs other
dependencies to roll ahead with it.

Manually roll DEPS to get past test failure

---

DEPS

https://github.com/KhronosGroup/SPIRV-Cross.git
/compare/4104e363005a..146dc453bcec
git log 4104e363005a079acc215f0920743a8affb31278..146dc453bcecc2d24721461a2d100e154f41dc76 --date=short --no-merges --format=%ad %ae %s
2019-06-17 post@arntzen-software.no MSL: Conditionally validate MSL 2.2 shaders.
2019-06-14 post@arntzen-software.no MSL: New SDK errors out on cull distance.
The AutoRoll server is located here: https://autoroll.skia.org/r/spirv-cross-shaderc-autoroll

Roll third_party/spirv-cross 4104e363005a..146dc453bcec (2 commits)

---

DEPS

https://github.com/KhronosGroup/glslang.git
/compare/def9662348b0..9db72785beb3
git log def9662348b029a6578f7fa9f46fde0e605b3a6c..9db72785beb33a89729d801249b23fdda79ae91d --date=short --no-merges --format=%ad %ae %s
2019-06-17 siglesias@igalia.com Delete duplicated gl_SubGroupSizeARB builtin treatment
The AutoRoll server is located here: https://autoroll.skia.org/r/glslang-shaderc-autoroll

Roll third_party/glslang def9662348b0..9db72785beb3 (1 commits)

---

DEPS

Roll third_party/glslang/ 9db72785b..f9d08a25f (6 commits)
https://github.com/KhronosGroup/glslang/compare/9db72785beb3...f9d08a25fbe1
$ git log 9db72785b..f9d08a25f --date=short --no-merges --format='%ad %ae %s'
2019-06-18 cepheus Bump revision.
2019-06-17 cepheus AST/SPV: Fix #930: translate uvec4 <-> uint64 for SubgroupGeMask et. al.
2019-06-18 cepheus Bump revision.
2019-06-17 cepheus SPV: Add a switch for favoring non-NaN operands in min, max, and clamp.
2019-06-17 cepheus Bump revision.
2019-02-17 jbolz Add Float16/Int8/Int16 capabilities for private variables and function parameters
Roll third_party/googletest/ 176eccfb8..ee32b72e1 (12 commits)
https://github.com/google/googletest/compare/176eccfb8f42...ee32b72e1204
$ git log 176eccfb8..ee32b72e1 --date=short --no-merges …

Rolling 4 dependencies

---

CHANGES
glslc/src/main.cc
glslc/test/option_dash_fnan_clamp.py
glslc/test/parameter_tests.py
libshaderc/include/shaderc/shaderc.h
libshaderc/include/shaderc/shaderc.hpp
libshaderc/src/common_shaders_for_test.h
libshaderc/src/shaderc.cc
libshaderc/src/shaderc_cpp_test.cc
libshaderc/src/shaderc_test.cc
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/src/compiler.cc
libshaderc_util/src/compiler_test.cc

Tells the compiler to generate code for max and min builtins so that
when given a NaN operand, the builtin returns the other operand.
Similarly, the clamp builtin will favour the non-NaN operands, as
if clamp were implemented as a composition of max and min.

Add -fnan-clamp

---

libshaderc_spvc/include/shaderc/spvc.h
libshaderc_spvc/include/shaderc/spvc.hpp
libshaderc_spvc/src/spvc.cc

The downstream users that use this method have been updated.
Fixes #673

Remove SetShaderModel from API

---

README.md

Point back to the Downloads section instead.
Partially addresses #731

Remove Appveyor artifacts link.

---

spvc/test/CMakeLists.txt
spvc/test/run_spirv_cross_tests.py
spvc/test/run_spirv_cross_tests_wrapper.sh

Refactors all of the various bits of common state and operations for
the tests into a single class. This reduces the amount of arg passing
that needs to occur, which in turn makes the code more readable.
The arguments to the script are filtered through this new class, so
that test code does not need to directly touch the parsed args, which
can be error prone.
Additionally the inputs to the script are changed from being all of
the binaries to use + the test file directory, to the directory where
the binaries are built + the test file directory.
Finally, the existing logging path is commented out, since it is
mostly broken under multiprocessing. An issue for fixing this has been
filed.
Fixes #735

Extract common test environment bits out into a class

---

spvc/test/run_spirv_cross_tests.py

Controls the amount of paralellism being used to run tests. Mostly
useful for forcing to single threaded mode while debugging.
Fixes #736

Add jobs flag to spirv cross tests script

---

DEPS

https://github.com/KhronosGroup/SPIRV-Cross/compare/02b2a1015d2b...d1bdb6d49144
$ git log 02b2a1015..d1bdb6d49 --date=short --no-merges --format='%ad %ae %s'
2019-06-27 post Run format_all.sh.
2019-06-27 post HLSL: Does not support case-fallthrough.
2019-06-27 post Handle more cases with FP16 and texture sampling.
2019-06-26 post Add C API for get_declared_struct_member_size.
2019-06-26 post MSL: De-virtualize get_declared_struct_member_size.
Created with:
roll-dep third_party/effcee third_party/glslang third_party/googletest third_party/re2 third_party/spirv-cross third_party/spirv-headers third_party/spirv-tools

Roll third_party/spirv-cross/ 02b2a1015..d1bdb6d49 (5 commits)

---

glslc/README.asciidoc
glslc/src/main.cc
glslc/test/parameter_tests.py
libshaderc/include/shaderc/env.h
libshaderc/include/shaderc/shaderc.h
libshaderc/include/shaderc/shaderc.hpp
libshaderc/src/shaderc.cc
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/src/compiler.cc
libshaderc_util/src/compiler_test.cc

Adds shaderc_compile_options_set_targte_spirv and associated enums.
Defaults to SPIR-V 1.0.
Passes that down into Glslang so we generate a module with the
specified version of SPIR-V.
Refactor how we map to Glslang target and client, and test that
better.
Setting spirv version is just an override.
Plumb through to glslc

Add --target-spv option to set target SPIR-V version

---

DEPS
spvc/test/known_failures

Roll third_party/glslang/ 4162de4bb..4b4b41a63 (5 commits)
https://github.com/KhronosGroup/glslang/compare/4162de4bbfc5...4b4b41a63499
$ git log 4162de4bb..4b4b41a63 --date=short --no-merges --format='%ad %ae %s'
2019-07-03 cepheus HLSL: Fix #1815: Don't constant fold spec-constant array indexing.
2019-07-02 jbolz update spirv-headers to pick up demote_to_helper_invocation
2019-07-02 cepheus Standalone: Fix #1814: Check that linkage was specified for reflection.
2019-07-02 cepheus Build: Tweak PR #1808 to avoid an implicit conversion warning.
2019-07-01 jbolz Implement GL_EXT_demote_to_helper_invocation
Roll third_party/spirv-cross/ 8ee8e60f7..9a6e2534e (4 commits)
https://github.com/KhronosGroup/SPIRV-Cross/compare/8ee8e60f70f9...9a6e2534e97a
$ git log 8ee8e60f7..9a6e2534e --date=short …

Rolling 4 dependencies and updating known_failures

---

DEPS
spvc/test/known_failures

Roll third_party/re2/ 848dfb7e1..e356bd3f8 (6 commits)
https://github.com/google/re2/compare/848dfb7e1d7b...e356bd3f80e0
$ git log 848dfb7e1..e356bd3f8 --date=short --no-merges --format='%ad %ae %s'
2019-07-07 junyer Make RE2::Set canonicalize DFA states.
2019-07-05 junyer Fix SimplifyStringSet() for really reals. And the test.
2019-07-04 junyer Don't let Prefilter::OrStrings() return NULL.
2019-07-04 junyer Fix SimplifyStringSet() properly. Ensure test coverage.
2019-07-04 junyer Fix a typographical error.
2019-07-04 junyer Stop SimplifyStringSet() from finding "" in everything.
Roll third_party/spirv-cross/ 9a6e2534e..53ab2144b (7 commits)
https://github.com/KhronosGroup/SPIRV-Cross/compare/9a6e2534e97a...53ab2144b90a
$ git log 9a6e2534e..53ab2144b --date=short --no-merges --format='%ad …

Rolling 4 dependencies and update known_failures

---

spvc/test/run_spirv_cross_tests.py

Add verbose flag to run_spirv_cross_tests.py

---

android_test/test.cpp

Since NDK 15b, that has been deprecated.  Remove it now from our
test code to avoid the deprecation warning.
See https://github.com/android-ndk/ndk/issues/381

Remove app_dummy call in Android test

---

utils/git-sync-deps

On few distributions Python is still being symlinked to Python 2 if it is installed.
Because this script only works on Python 3, we can simply ask for it directly.

Explicitly use python3 for git-sync-deps

---

libshaderc_util/src/spirv_tools_wrapper.cc

Use more relaxed rules for HLSL validation. See https://github.com/KhronosGroup/SPIRV-Tools/pull/2546 for more background.

SetBeforeHlslLegalization to use more relaxed validation rules

---

libshaderc/src/shaderc.cc

The extra semicolons will be treat as warning error if build shaderc as a third party library.

Remove extra semicolons in shaderc

---

DEPS
spvc/test/known_failures

Also updated known_failures
Roll third_party/glslang/ 3cea2e588..37fc4d27d (4 commits)
https://github.com/KhronosGroup/glslang/compare/3cea2e5882e3...37fc4d27d612
$ git log 3cea2e588..37fc4d27d --date=short --no-merges --format='%ad %ae %s'
2019-08-09 rharrison Make non-emscripten flags platform agnostic.
2019-08-09 rharrison Converted ENABLE_HLSL to a dependent option, so it can be always disabled in web builds
2019-08-09 rharrison Move build instructions to README.md
2019-08-08 rharrison Add WASM build target for Web version of glslang
Roll third_party/googletest/ b4961ab1c..90a443f9c (6 commits)
https://github.com/google/googletest/compare/b4961ab1cbda...90a443f9c243
$ git log b4961ab1c..90a443f9c --date=short --no-merges --format='%ad %ae %s'
2019-08-07 absl-team Googletest export …

Rolling 3 dependencies

---

libshaderc_spvc/src/spvc.cc

-Wclass-memaccess warnings/errors is being triggered somewhat
spuriously. Coercing the type to avoid this warning, since this
should be valid.
Fixes #780

Explicitly cast fuzzing data to avoid new GCC warning

---

utils/update_build_version.py

Changes the behaviour of reading in the CHANGES file to insert
'?' when encountering non-ASCII, instead of throwing. Given that this
part of the code is just extracting the version string from CHANGES,
this should not have unicode in it. If a ? is getting inserted in
there, then the file is malformed and this operation will fail.
Also cleans up a usage of print.
Fixes #778

Fix some Python2 vs 3 issues in update_build_version.py

---

README.md
glslc/test/option_dash_fhlsl_offsets.py
libshaderc/src/common_shaders_for_test.h
libshaderc_util/CMakeLists.txt
libshaderc_util/src/compiler_test.cc

Fixes a compilation problem introduced by recent
Glslang changes to optionally build into a very small
GLSL-only binary.
Also fix test cases to have set and binding layout qualifiers on
buffers when compiling for Vulkan.  This rule is now enforced by
Glslang.

Force Glslang to support HLSL in its interface

---

libshaderc_spvc/src/spvc_private.h

All other projects using spirv-cross include it using <spirv_msl.hpp>
for example. Follow that convention so we can more easily integrate with
other projects.

Use agreed upon include paths for spirv-cross

---

libshaderc_spvc/src/spvc_private.cc

The environment should be the same as the source binary, not the
outputted binary.
Fixes #798

Pass in source not target env into spirv-opt

---

CMakeLists.txt
third_party/CMakeLists.txt

This does not appear to be standard practice. The results of these
checks would only change if the compiler itself changes, so checking
it on every run is unnecessary.
Fixes #773

Remove unsetting compiler check variables

---

spvc/test/known_failures
spvc/test/run_spirv_cross_tests.py

.nocompat. indicates that the test is known to be bad for GLSL, and is
skipped in the spirv-cross tests. Skipping these tests removes about
600 cases from the test runs.
.vk. indicates this is a Vulkan test case and .vk. indicates that this
is a SPIR-V based one. Passing in the same flags that the spriv-cross
tests use and handling that the output file will now have a .vk
appended.
Fixes #627

Improve testing .asm., .nocompat., and .vk. chases

---

known_good.json

Use SPIRV-Tools stable commit from 2019-09-04, plus two commits
more, fixing SPIRV-Tools issue 2833

Update all components

---

DEPS
spvc/test/known_failures

Roll third_party/effcee/ 6527fb254..cd25ec17e (2 commits)
https://github.com/google/effcee/compare/6527fb25482e...cd25ec17e938
$ git log 6527fb254..cd25ec17e --date=short --no-merges --format='%ad %ae %s'
2019-09-18 dneto Start v2019.1-dev
2019-09-18 dneto Finalize v2019.0
Roll third_party/glslang/ 664ad418f..caca1d1cc (12 commits)
https://github.com/KhronosGroup/glslang/compare/664ad418f845...caca1d1cc46e
$ git log 664ad418f..caca1d1cc --date=short --no-merges --format='%ad %ae %s'
2019-09-17 cepheus SPV_KHR_physical_storage_buffer/SPV: Add GL_EXT_buffer_reference_uvec2
2019-09-16 digit Fix Fuchsia build.
2019-09-18 cepheus README: Fix WASM typos.
2019-09-18 cepheus HLSL: Fix #1903 Catch 0-argument case to constructors.
2019-09-08 jbolz Add GL_EXT_shader_subgroup_extended_types support …

Rolling 6 dependencies and update known_failures

---

DEPS

Roll third_party/glslang/ caca1d1cc..973d0e538 (3 commits)
https://github.com/KhronosGroup/glslang/compare/caca1d1cc46e...973d0e538292
$ git log caca1d1cc..973d0e538 --date=short --no-merges --format='%ad %ae %s'
2019-09-20 cepheus GLSL/SPV: Fix #1900: Drop const on literal when doing an object copy.
2019-09-17 kainino use custom es6 modularization instead of MODULARIZE=1
2019-09-17 kainino Separate GLSLANG_WEB (min-size build) and Emscripten options
Roll third_party/spirv-tools/ 08fcf8a4a..f62ee4a4a (8 commits)
https://github.com/KhronosGroup/SPIRV-Tools/compare/08fcf8a4abdc...f62ee4a4a1a1
$ git log 08fcf8a4a..f62ee4a4a --date=short --no-merges --format='%ad %ae %s'
2019-09-23 dneto Update DEPS: effcee, re2, googletest (#2881)
2019-09-23 dneto Add method comment for …

Rolling 2 dependencies

---

libshaderc_spvc/CMakeLists.txt
libshaderc_spvc/src/common_shaders_for_test.h
libshaderc_spvc/src/spvc.cc
libshaderc_spvc/src/spvc_private.cc
libshaderc_spvc/src/spvc_private.h
libshaderc_spvc/src/spvc_test.cc
libshaderc_spvc/src/spvc_webgpu_test.cc

Retains the compiler used for generating the platform shader in the
result. This will allow future patches to build up the reflection API,
which will require having access to the compiler.
Part of #818, #819, and #820

Add spvc compiler to returned result

---

libshaderc_spvc/CMakeLists.txt
libshaderc_spvc/src/common_shaders_for_test.h
libshaderc_spvc/src/spvc.cc
libshaderc_spvc/src/spvc_private.cc
libshaderc_spvc/src/spvc_private.h
libshaderc_spvc/src/spvc_test.cc
libshaderc_spvc/src/spvc_webgpu_test.cc

Reverts google/shaderc#821
This is needed because this PR exposed multiple issues related to spirv_cross inclusion. Specific exceptions can be included via header usage and issues with importing the reflect classes. I am going to roll this back, and investigate locally.

Revert "Add spvc compiler to returned result"

---

DEPS
spvc/test/known_failures

Roll third_party/spirv-cross/ 5431e1da2..e5d3a6655 (8 commits)
https://github.com/KhronosGroup/SPIRV-Cross/compare/5431e1da2dc1...e5d3a6655e13
$ git log 5431e1da2..e5d3a6655 --date=short --no-merges --format='%ad %ae %s'
2019-10-07 rharrison Update SPV_VERSION from 1.4 to 1.5
2019-10-07 post Workaround MSVC issue.
2019-10-07 post Do not consider aliased struct types if the master is not a block.
2019-10-07 post Run format_all.sh.
2019-10-04 post Do not value compare JSON files for regression purposes.
2019-10-04 post Reflect: Deal with workgroup size being specialization constants.
2019-10-03 frank.richter reference: Update to include workgroup_size
2019-10-03 frank.richter reflection: Write workgroup_size to JSON for compute shaders
Created with:
roll-dep third_party/spirv-cross
Fixes …

Roll spirv-cross ahead and update known_failures to fix build breakage

---

DEPS

Roll third_party/glslang/ 7bc047326..4b97a1108 (5 commits)
https://github.com/KhronosGroup/glslang/compare/7bc047326e06...4b97a1108114
$ git log 7bc047326..4b97a1108 --date=short --no-merges --format='%ad %ae %s'
2019-10-06 dj2 single line
2019-10-03 dj2 Update appveyor and travis files
2019-10-03 dj2 Move install directory for SPIRV/ folder.
2019-09-29 cepheus HLSL: Fix #1912: add attribute syntax for nonreadable/nonwritable
2019-09-27 cepheus HLSL: Fix #1912: add attribute syntax for overriding image formats.
Roll third_party/googletest/ dc1ca9ae4..cd17fa2ab (8 commits)
https://github.com/google/googletest/compare/dc1ca9ae4c20...cd17fa2abda2
$ git log dc1ca9ae4..cd17fa2ab --date=short --no-merges --format='%ad %ae %s'
2019-10-05 soap Add documentation for pkg-config in cross-compilation …

Rolling 5 dependencies

---

BUILD.gn
shaderc_features.gni

This will allow downstream embedders to use the default values for
flags.
The build override dirs have been left in place, since users need to
define them for their repo layout.

Add in shaderc_features.gni to support build time flags

---

DEPS
spvc/test/known_failures
spvc/test/known_invalids

Roll third_party/googletest/ cd17fa2ab..bdc29d5dc (19 commits)
https://github.com/google/googletest/compare/cd17fa2abda2...bdc29d5dc19d
$ git log cd17fa2ab..bdc29d5dc --date=short --no-merges --format='%ad %ae %s'
2019-10-16 absl-team Googletest export
2019-10-11 misterg Googletest export
2019-10-10 absl-team Googletest export
2019-10-10 absl-team Googletest export
2019-10-10 chrisjohnsonmail chore:  update version
2019-10-10 joshdcannon Made noexcept condition more exciting
2019-10-09 absl-team Googletest export
2019-10-09 zeb Mention Cornichon as a related open source project
2019-10-07 joshdcannon Use declval in noexcept expression
2019-10-07 joshdcannon Switch to free function to avoid GCC bug
2019-10-07 joshdcannon Avoid comma operator
2019-10-07 joshdcannon Fix spacing
2019-10-07 …

Rolling 5 dependencies and update known_failures & known_invalids

---

DEPS
spvc/test/known_failures
spvc/test/run_spirv_cross_tests.py
spvc/test/unconfirmed_invalids

Roll third_party/glslang/ a959deb00..834ee546f (1 commit)
https://github.com/KhronosGroup/glslang/compare/a959deb00750...834ee546f93d
$ git log a959deb00..834ee546f --date=short --no-merges --format='%ad %ae %s'
2019-10-17 jbolz Only apply volatile semantics to atomics when using Vulkan Memory Model
Roll third_party/googletest/ bdc29d5dc..f966ed158 (4 commits)
https://github.com/google/googletest/compare/bdc29d5dc19d...f966ed158177
$ git log bdc29d5dc..f966ed158 --date=short --no-merges --format='%ad %ae %s'
2019-10-18 misterg Googletest export
2019-10-17 absl-team Googletest export
2019-10-17 absl-team Googletest export
2019-10-09 robert Add more override keywords
Roll third_party/spirv-cross/ a92668bc1..ff1897ae0 (1 commit)
https://github.com/KhronosGroup/SPIRV-Cross/compare/a92668bc118a …

Rolling 4 dependencies, small script fix and updating expectation files

---

.gitignore
Android.mk

Also ignore android_test/include, as that is updated during
test builds.
Fixes https://github.com/android/ndk/issues/1105

Android.mk: Install all necessary headers

---

DEPS
spvc/test/known_failures
spvc/test/unconfirmed_invalids

Roll third_party/glslang/ 834ee546f..b131630e7 (16 commits)
https://github.com/KhronosGroup/glslang/compare/834ee546f93d...b131630e7c74
$ git log 834ee546f..b131630e7 --date=short --no-merges --format='%ad %ae %s'
2019-10-24 greg Update spirv-tools known good.
2019-10-23 ehsannas Make  buildbot licenses consistent with the rest of the code
2019-10-23 52076061+digit-google BUILD.gn: Fix fuchsia build (#1944)
2019-10-21 cepheus Web: Reclaim more space and make all work w/wo GLSLANG_WEB.
2019-10-18 cepheus Web: Add basic atomics for SSBOs.
2019-10-17 cepheus Web: Add SSBOs and a few other missing compute features.
2019-10-10 cepheus Web: Add compute stage.
2019-10-08 cepheus Web: Add separate texture/sampler, exclude *CubeArray*.
2019-10-22 47668180+tsuoranta Enable generation of …

Rolling 5 dependencies & expectation files

---

libshaderc_spvc/include/spvc/spvc.h
libshaderc_spvc/include/spvc/spvc.hpp
libshaderc_spvc/src/spvc.cc
libshaderc_spvc/src/spvcir_pass.cc
spvc/src/main.cc
spvc/test/known_failures
spvc/test/run_spirv_cross_tests.py

Add --emit-line-directive option to spvc test script
Setting "run_on_debug_line_insts" to true in ForEachInst to avoid skipping OpLine instructions while parsing in spvcir pass
Removing 6 tests from known_failure which succeed as a result of adding this option

Add --emit-line-drective option

---

libshaderc_spvc/src/spvcir_test.cc

Refactors and adds unit tests for the following instructions:
- OpCapability
- OpExtension
- OpMemoryModel
- OpEntryPoint
- OpTypeVoid
- OpTypeFunction
- OpFunction
- OpLabel
- OpReturn

Add unit test for spvcir parser

---

libshaderc_spvc/include/spvc/spvc.h
libshaderc_spvc/include/spvc/spvc.hpp
libshaderc_spvc/src/spvc.cc
libshaderc_spvc/src/spvc_cpp_test.cc
libshaderc_spvc/src/spvc_webgpu_cpp_test.cc
spvc/src/main.cc

Dawn, the only known consumer of this API, has migrated away from
using these functions/classes/types.

Remove deprecated API elements

---

libshaderc_spvc/include/spvc/spvc.h
libshaderc_spvc/include/spvc/spvc.hpp
libshaderc_spvc/src/spvc.cc
libshaderc_spvc/src/spvc_cpp_test.cc
libshaderc_spvc/src/spvc_private.cc
libshaderc_spvc/src/spvc_private.h
libshaderc_spvc/src/spvc_smoke_test_util.c
libshaderc_spvc/src/spvc_test.cc
libshaderc_spvc/src/spvc_webgpu_cpp_test.cc
libshaderc_spvc/src/spvc_webgpu_test.cc
spvc/src/main.cc

The current API does all of the validation, IR generation, and cross
compile in a single operation. Third party users, specifically Dawn,
want to be able to insert their own commands between the IR generation
and compilation stages. Thus the API is being broken up into two
commands, an initialization command that validates input and generates
the IR, and a compile command that actually performs the cross
compile.
Fixes #863

Split spvc shader generation into initialize and compile phases

---

third_party/Android.mk

This is needed to fix building according to instructions at
https://developer.android.com/ndk/guides/graphics/shader-compilers#Getting%20The%20Latest

Android.mk: Fix detection of spirv-headers directory

---

Android.mk

When installing shaderc headers, do that only as a dependency
of libshaderc_combined.

Android.mk: Avoid polluting NDK build's test tree.

---

BUILD.gn

This will brielfy break things upstream, but this is kinda
unavoidable.

Convert to using standard spirv_cross deps in BUILD.gn

---

BUILD.gn

This reverts commit eca11511a0c09dd599837862c96658a91e927a3a.

Revert "Convert to using standard spirv_cross deps in BUILD.gn (#902)"

---

BUILD.gn

This is being done to allow removal of one of its upstream
dependencies. This is part of a larger effort to eliminate the
cyclical dependency that exists between Dawn and spvc.
Part of the work for #906

Disable shaderc library target in BUILD.gn

---

BUILD.gn
libshaderc_spvc/CMakeLists.txt
libshaderc_spvc/src/spvc_private.cc

This is to remove transitive dependency on glslang that this is
pulling in.
Fixes #913

Remove spvc's dependency on shaderc's util library

---

libshaderc_spvc/include/spvc/spvc.h
libshaderc_spvc/include/spvc/spvc.hpp
libshaderc_spvc/src/spvc.cc
libshaderc_spvc/src/spvc_cpp_test.cc
libshaderc_spvc/src/spvc_private.cc
libshaderc_spvc/src/spvc_private.h
libshaderc_spvc/src/spvc_smoke_test_util.c
libshaderc_spvc/src/spvc_test.cc
libshaderc_spvc/src/spvc_webgpu_cpp_test.cc
libshaderc_spvc/src/spvc_webgpu_test.cc

These currently proxy to the previous shaderc ones, so that downstream
integrators are not broken by this change. Once integrators have
migrated, proper distinct enums will be used.
Part of #916

Create spvc specific return codes and use them

---

libshaderc_spvc/include/spvc/spvc.h
libshaderc_spvc/include/spvc/spvc.hpp
libshaderc_spvc/src/spvc.cc
libshaderc_spvc/src/spvc_private.cc
libshaderc_spvc/src/spvc_private.h

Missed this in the review of the initial patch, probably a rebasing/patch timing issue.

Change from old status type in the API

---

DEPS
spvc/test/known_spvc_failures
spvc/test/unconfirmed_invalids

Roll third_party/glslang/ 38b4db48f..0de87ee9a (6 commits)
https://github.com/KhronosGroup/glslang/compare/38b4db48f98c...0de87ee9a5bf
$ git log 38b4db48f..0de87ee9a --date=short --no-merges --format='%ad %ae %s'
2019-12-04 rnk Remove glslang::pool_allocator::setAllocator
2019-01-21 ian.d.romanick INTEL_shader_integer_functions2: Add SPIR-V generation
2018-09-20 ian.d.romanick INTEL_shader_integer_functions2: Add compiler front-end support
2018-09-20 ian.d.romanick INTEL_shader_integer_functions2: Add basic extension tracking
2019-12-02 ian.d.romanick Update README.md to include other test requirements
2019-11-27 malcolm.bechard Fix #1981
Roll third_party/googletest/ 679bfec6d..ae8d1fc81 (14 commits)
https://github.com/google/googletest/compare/679bfec6db73...ae8d1fc81b14
$ git log …

Rolling 4 dependencies & updating expectations

---

libshaderc_spvc/src/spvcir_pass.cc

- remove useless std::move on a const std::string variable
- remove redundant return at end of void function

Apply clang-tidy advice

---

libshaderc_spvc/CMakeLists.txt

Use ${<project>_BINARY_DIR} for built headers for spirv-tools.
Use ${<project>_SOURCE_DIR} for source headers for effcee and RE2.
CMake generates those variables automatically.

Don't assume locations of spirv-tools, effcee, and RE2 are located

---

libshaderc_spvc/include/spvc/spvc.hpp
libshaderc_spvc/src/spvc.cc

This is needed to support allowing the user to pass in things like
lambdas with captures, instead of just raw function pointers.
Fixes #935

Implement a C++ only version for ForEachCombinedImageSamplers

---

libshaderc_spvc/include/spvc/spvc.h
libshaderc_spvc/include/spvc/spvc.hpp
libshaderc_spvc/src/spvc.cc

I originally championed the callback style interface that has been implemented, but it has become difficult to integrate into Dawn correctly. 
So I think @dj2's suggestion of a data return interface is the better way to go now.

Replace callback interface with data one for combined image samplers

---

DEPS
spvc/test/known_failures
spvc/test/known_spvc_failures

Roll third_party/glslang/ ebf634bca..40801e31e (8 commits)
https://github.com/KhronosGroup/glslang/compare/ebf634bcaa3e...40801e31ed0c
$ git log ebf634bca..40801e31e --date=short --no-merges --format='%ad %ae %s'
2020-01-06 cepheus Bump revision
2020-01-06 laddoc Add builtin constants
2019-12-26 cepheus HLSL: Fix #2037: Integer dot used incorrect input for adds.
2019-12-25 laddoc atomic counter offset should align to 4
2019-11-26 laddoc Add support for ARB_uniform_buffer_object
2019-11-26 laddoc Add support for ARB_texture_multisample
2019-11-26 laddoc Add support for ARB_sample_shading
2019-12-20 cepheus Command-line: Give better error messages. From #1829.
Roll third_party/googletest/ 5b162a79d..306f3754a (17 commits)
https://github.com/google/googletest/compare/5b162a79d49d...306f3754a7 …

Rolling 5 dependencies and updating expectations

---

libshaderc_spvc/src/spvc.cc
libshaderc_spvc/src/spvc_private.cc
libshaderc_spvc/src/spvc_private.h

This is mostly done so that code adding messages doesn't need to remember to put
a '\n' after, like they are a telegraph operator or something.
Part of resolving #951

Convert spvc messages internal struct to be a vector

---

libshaderc_spvc/src/spvc.cc

Doing this so I can correct an issue with returning a local reference
in the failure case.
Fixes #954

Convert get_shader_resources to return ptr instead of ref

---

DEPS
glslc/src/main.cc
glslc/test/option_target_env.py
glslc/test/parameter_tests.py
libshaderc/include/shaderc/env.h
libshaderc/src/shaderc.cc
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/src/compiler.cc
libshaderc_util/src/compiler_test.cc
libshaderc_util/src/spirv_tools_wrapper.cc

Compiling for Vulkan 1.2 defaults to using SPIR-V 1.5.
Depends on Vulkan 1.2 support in Glslang, and SPIRV-Tools
Depends on SPIR-V 1.5 support in SPIRV-Headers

Support Vulkan 1.2

---

DEPS
spvc/test/known_failures
spvc/test/known_spvc_failures

Roll third_party/glslang/ 4fc7a3391..b0ada8035 (3 commits)
https://github.com/KhronosGroup/glslang/compare/4fc7a33910fb...b0ada80356ca
$ git log 4fc7a3391..b0ada8035 --date=short --no-merges --format='%ad %ae %s'
2020-01-17 cepheus HLSL: Fix #1974: ignore input primitives on non-entry-point functions.
2020-01-16 cepheus Fix #2059, and also attempt to skip test bots [skip ci]
2019-12-24 laddoc Add Error check flag in io mapper
Roll third_party/googletest/ d854bd6ac..8b4817e3d (6 commits)
https://github.com/google/googletest/compare/d854bd6acc47...8b4817e3df37
$ git log d854bd6ac..8b4817e3d --date=short --no-merges --format='%ad %ae %s'
2020-01-15 absl-team Googletest export
2020-01-15 absl-team Googletest export
2020-01-14 absl-team Googletest export
2020-01-14 absl-team Googletest export …

Rolling 3 dependencies and updating expectations

---

libshaderc_spvc/include/spvc/spvc.h
libshaderc_spvc/include/spvc/spvc.hpp
libshaderc_spvc/src/spvc.cc
libshaderc_spvc/src/spvc_smoke_test_util.c

All functions now return a status value, and use out params to return data.
All functions now check state objects and in/out pointers for validity.

Big cleanup to normalize API behaviour

---

DEPS
spvc/test/known_failures
spvc/test/known_spvc_failures

Roll third_party/glslang/ 965bd4d96..19ec0d2ff (4 commits)
https://github.com/KhronosGroup/glslang/compare/965bd4d96613...19ec0d2ff905
$ git log 965bd4d96..19ec0d2ff --date=short --no-merges --format='%ad %ae %s'
2020-01-27 cepheus Build: Fix more build warnings caused by PR #2038.
2020-01-26 cepheus Build warning: Fix #2062, missing enum value in a switch.
2019-12-24 laddoc Add Tess machine dependent built-in variables initialization for GLES 3.2
2019-10-18 timo.suoranta Fixes for gcc 9 / -Werror=deprecated-copy
Roll third_party/googletest/ 8b4817e3d..10b1902d8 (6 commits)
https://github.com/google/googletest/compare/8b4817e3df37...10b1902d893e
$ git log 8b4817e3d..10b1902d8 --date=short --no-merges --format='%ad %ae %s'
2020-01-21 absl-team Googletest export
2020-01-17 absl-team …

Rolling 5 dependencies and updated exceptions

---

libshaderc_spvc/include/spvc/spvc.hpp

Due to complex dependencies between us, glslang, and Dawn, downstream
users that cannot roll Dawn ahead right now need these APIs present,
so that they can still roll glslang & shaderc.

Add back in deprecated spvc APIs

---

glslc/src/main.cc
glslc/test/parameter_tests.py

Long ago, compilers emitted assembly text, then called an assembler
stage to create the binary.
So, for example, clang describes its -S option as:
-S   Only run preprocess and compilation steps
But that's very confusing these days.
Change the description for glslc -S from that old one to:
-S   Emit SPIR-V assembly instead of binary.
The README.asciidoc already describes -S well.

Better help for glslc -S

---

DEPS
spvc/test/known_failures
spvc/test/known_spvc_failures

Roll third_party/glslang/ 19ec0d2ff..5e86b28ff (3 commits)
https://github.com/KhronosGroup/glslang/compare/19ec0d2ff905...5e86b28ffb81
$ git log 19ec0d2ff..5e86b28ff --date=short --no-merges --format='%ad %ae %s'
2020-01-29 jbolz Use NOT ... VERSION_LESS instead of VERSION_GREATER_EQUAL
2020-01-28 jordan.l.justen standalone: Fix --help
2020-01-27 rharrison Use correct enum type in case statement
Roll third_party/re2/ 85c014206..05faa8db3 (2 commits)
https://github.com/google/re2/compare/85c014206aee...05faa8db3a96
$ git log 85c014206..05faa8db3 --date=short --no-merges --format='%ad %ae %s'
2020-01-31 junyer Avoid using the forward DFA in "ANCHOR_END" cases.
2020-01-29 junyer Make the fuzzer use FuzzedDataProvider.
Roll third_party/spirv-cross/ 68bf0f824..6b2add8e2 (4 commits) …

Rolling 4 dependencies and updated expectations

---

libshaderc_spvc/src/spvc.cc

Lots of common checking and logging code had been factored out into some macros,
and just spamming those as the beginning of methods instead.

Reduce amount of duplicated code in API implementations

---

DEPS
spvc/test/known_failures
spvc/test/known_spvc_failures

Roll third_party/glslang/ 5e86b28ff..c12493ff6 (10 commits)
https://github.com/KhronosGroup/glslang/compare/5e86b28ffb81...c12493ff69e2
$ git log 5e86b28ff..c12493ff6 --date=short --no-merges --format='%ad %ae %s'
2020-02-17 siglesias SPV_AMD_shader_image_load_store_lod is now validated by spirv-tools
2020-02-19 lryer Fix iomapper issue
2020-02-11 cepheus Fix part of #2070: Correctly handle promotion for <unary-op>(int).
2020-02-18 swda.durl Add an option to make RTTI enabled
2020-02-06 kainino Split "is emscripten" config from "enable glslang.js"
2020-02-06 dneto Avoid enum-compare warning
2020-02-06 rex.xu Fix a parser error of GL_KHR_memory_scope_semantics
2020-01-23 kainino glslang.js: Make the SPIR-V target version configurable (1.0 ~ 1.5)
2020-02-02 timo.suoranta Fix memory …

Rolling 6 dependencies and update expectations

---

DEPS
spvc/test/known_failures
spvc/test/known_spvc_failures
spvc/test/unconfirmed_invalids

Roll third_party/glslang/ c12493ff6..56364b6b6 (7 commits)
https://github.com/KhronosGroup/glslang/compare/c12493ff69e2...56364b6b6026
$ git log c12493ff6..56364b6b6 --date=short --no-merges --format='%ad %ae %s'
2020-03-01 cepheus Copyright update, mostly to trigger bots again.
2020-03-01 cepheus Fix #2095: correct the indentation.
2020-02-28 cepheus Fix #1461: set the SPIRV-Tools' optimizer's target environment.
2020-02-28 cepheus Fix #2091, remove incorrect assert for division by 0.0.
2020-02-28 wangli28 Add vcpkg installation instructions
2020-02-28 sk Fix for #2075: removed DefaultTBuiltInResource from glslang_c_interface.cpp
2020-02-22 rex.xu Fix an issue of SPV generation for imageAtomicStore.
Roll third_party/googletest/ 23b2a3b1c..e588eb1ff (3 commits) …

Rolling 6 dependencies and updating expectations

---

CMakeLists.txt
glslc/src/shader_stage.cc
glslc/src/stage_test.cc
libshaderc/Android.mk
libshaderc/include/shaderc/shaderc.h
libshaderc/src/common_shaders_for_test.h
libshaderc/src/shaderc.cc
libshaderc/src/shaderc_private.h
libshaderc/src/shaderc_private_test.cc
libshaderc/src/shaderc_test.cc
libshaderc_spvc/Android.mk
libshaderc_util/Android.mk
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/src/shader_stage.cc

This has been removed from glslang a while ago and is no longer needed.

Remove NV_EXTENSIONS conditionals

---

DEPS

Roll third_party/glslang/ 1f0fcbe5a..8e26c5f50 (26 commits)
$ git log 1f0fcbe5a..8e26c5f50 --date=short --no-merges --format='%ad %ae %s'
2020-03-25 neslisah.torosdagli@amd.com switch format update
2020-03-24 neslisah.torosdagli@amd.com copyright notice changes removed from unchanged files
2020-03-24 neslisah.torosdagli@amd.com copyright notice changes removed from unchanged files
2020-03-24 neslisah.torosdagli@amd.com copyright notice changes removed from unchanged files
2020-03-24 neslisah.torosdagli@amd.com spirv.hpp reverted to commit f368dcbb7d8af23f0cba3015d0f4dda9dc3aa66d
2020-03-24 neslisah.torosdagli@amd.com .travis updated to origin, rayQueryCheck removed
2020-03-23 neslisah.torosdagli@amd.com const rayFlag defs used in the test cases in stead of numerical values
2020-03-23 …

Roll glslang dependency

---

libshaderc_spvc/include/spvc/spvc.h
libshaderc_spvc/include/spvc/spvc.hpp
libshaderc_spvc/src/spvc.cc
libshaderc_spvc/src/spvc_smoke_test_util.c
libshaderc_spvc/src/spvc_test.cc
libshaderc_spvc/src/spvc_webgpu_cpp_test.cc
libshaderc_spvc/src/spvc_webgpu_test.cc
spvc/src/main.cc

This is designed to replace the existing code which has default values, and
setters, with a pattern that requires specifying the environments at creation
time.
All of the internal code and tests has been updated to use the new API.
The old API has been marked as a deprecated and will be removed once Dawn no
longer uses it.
Part of #1017

Convert compile options to require explicit environments

---

known_good.json

Tested with Android NDK build as well.

Update to SPIRV-Tools 2020.2 fixes miscompile

---

libshaderc/src/shaderc.cc
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/include/libshaderc_util/spirv_tools_wrapper.h
libshaderc_util/src/compiler.cc
libshaderc_util/src/spirv_tools_wrapper.cc

For the WebGPUI environment, when generating SPIR-V first generate Vulkan1.1
SPIR-V, and then use the optimizer to convert it to WebGPU SPIR-V, since glslang
cannot natively emit it.
Fixes #1020

Add support for WebGPU to shaderc

---

DEPS
spvc/test/known_failures
spvc/test/known_spvc_failures

Roll third_party/glslang/ ad1b588de..08c02ced7 (1 commit)
https://github.com/KhronosGroup/glslang/compare/ad1b588deac6...08c02ced798a
$ git log ad1b588de..08c02ced7 --date=short --no-merges --format='%ad %ae %s'
2020-03-30 dsinclair Remove unused variables.
Roll third_party/googletest/ 749148f1a..67cc66080 (3 commits)
https://github.com/google/googletest/compare/749148f1accc...67cc66080d64
$ git log 749148f1a..67cc66080 --date=short --no-merges --format='%ad %ae %s'
2020-03-23 absl-team Googletest export
2019-07-11 adam.f.badura Add support for std::function in MockFunction (#2277)
2019-12-26 adam.f.badura Add tests for MockFunction deduction (#2277)
Roll third_party/re2/ ca93436e5..209eda1b6 (2 commits)
https://github.com/google/re2/compare/ca93436e5b1b...209eda1b6079
$ git log …

Rolling 5 dependencies and updated expectations

---

DEPS

dkoch$ git log 08c02ced..e157435c1 --date=short --no-merges --format='%ad %ae %s'
2020-03-31 cepheus@frii.com Bump revision.
2020-03-30 alele@nvidia.com Error assigns to objects of rayQueryEXT type.
cc @zoddicus @dneto0 @s-perron

update glslang to SDK-Candidate-2 tag

---

libshaderc_spvc/include/spvc/spvc.h
libshaderc_spvc/src/spvc.cc

This exposes the data that is available from variable_is_depth_or_compar for
Dawn.
Fixes #1034

Add concept of comparison sampler to API

---

DEPS
libshaderc_spvc/src/spvcir_pass.cc
libshaderc_spvc/src/spvcir_test.cc
spvc/test/known_failures
spvc/test/known_spvc_failures
spvc/test/unconfirmed_invalids

Roll third_party/glslang/ 3f4e5c456..f03cb290a (9 commits)
https://github.com/KhronosGroup/glslang/compare/3f4e5c456306...f03cb290ac10
$ git log 3f4e5c456..f03cb290a --date=short --no-merges --format='%ad %ae %s'
2020-04-27 63069047+pmistryNV Add support for extension GL_ARB_texture_query_lod. (#2194)
2020-04-28 dj2 Remove unused Es310Desktop430 (#2200)
2020-04-27 63069047+pmistryNV Add support for extension GL_ARB_shading_language_packing (#2192)
2020-04-27 cepheus Move to SPIR-V 1.5 Rev. 3, bump revision, remove a status from README.
2020-04-24 johnkslang Note about Build Status.
2020-04-24 cepheus Move to latest SPIR-V header, and bump glslang revision.
2020-04-22 63069047+pmistryNV Add support for extension GL_ARB_shader_storage_buffer_object (#2184)
2020-04-22 antidote.crk TPpToken: …

Rolling 5 dependencies, updating expectations, and fixing build issues

---

DEPS
libshaderc_util/src/resources.cc

Roll third_party/glslang/ f03cb290a..b5f003d7a (7 commits)
https://github.com/KhronosGroup/glslang/compare/f03cb290ac10...b5f003d7a3ec
$ git log f03cb290a..b5f003d7a --date=short --no-merges --format='%ad %ae %s'
2020-05-01 cepheus Fix #2191: Error check for indexing reference containing unsize array.
2020-05-01 cepheus GLSL: Separate out swizzle handling (potentially fixing bugs).
2020-04-21 pmistry Add support for es extension GL_EXT_blend_func_extended * Introduces builtin variables gl_SecondaryFragColorEXT and gl_SecondaryFragDataEXT * Introduces builtin constant gl_MaxDualSourceDrawBuffersEXT * enables support for layout qualifier "index" in es profile
2020-04-30 63069047+pmistryNV Add support for extension GL_EXT_shader_integer_mix (#2203)
2020-04-26 pmistry Add support for …

Rolling 5 dependencies and fixing build

---

DEPS
spvc/test/known_failures
spvc/test/known_spvc_failures

Roll third_party/re2/ 52b4b94b0..787495f0b (4 commits)
https://github.com/google/re2/compare/52b4b94b00f0...787495f0ba2e
$ git log 52b4b94b0..787495f0b --date=short --no-merges --format='%ad %ae %s'
2020-05-22 junyer Use CMAKE_CXX_STANDARD now that we can.
2020-05-22 junyer Make "front and back" prefix accel work with MSVC.
2020-05-22 junyer Rename to Regexp::RequiredPrefixForAccel().
2020-05-22 junyer Add a basic test for prefix accel.
Roll third_party/glslang/ 2cf9621d6..2b0eafb1d (1 commit)
https://github.com/KhronosGroup/glslang/compare/2cf9621d6d6f...2b0eafb1de5b
$ git log 2cf9621d6..2b0eafb1d --date=short --no-merges --format='%ad %ae %s'
2020-05-25 alanbaker Update spirv tools (#2246)
Roll third_party/spirv-cross/ 287e93ff8..61cddd630 (3 commits) …

Rolling 4 dependencies and expectations

---

DEPS

https://github.com/KhronosGroup/SPIRV-Cross/compare/61cddd6307ef...d385bf096f5d
$ git log 61cddd630..d385bf096 --date=short --no-merges --format='%ad %ae %s'
2020-05-28 bryan.bernhart Prefer set/binding API
2020-05-28 post Document all CLI options.
2020-05-28 post Do not mask writes to remapped variables in all cases.
2020-05-27 bryan.bernhart HLSL: Add option to treat certain SSBO bindings as UAV, even with readonly.
Created with:
roll-dep third_party/spirv-cross

Roll third_party/spirv-cross/ 61cddd630..d385bf096 (4 commits)

---

libshaderc_spvc/include/spvc/spvc.h
libshaderc_spvc/include/spvc/spvc.hpp
libshaderc_spvc/src/spvc.cc

Adds support for the corresponding SPIRV-Cross API [1] introduced to resolve WebGPU/Dawn issue related to forcing UAVs.
[1] https://github.com/KhronosGroup/SPIRV-Cross/issues/1368

Support forcing storage buffers to be always declared as UAV

---

libshaderc_spvc/include/spvc/spvc.h
libshaderc_spvc/src/spvc.cc

In dawn, we need to validate buffer sizes for uniform and storage buffers to make sure bound buffers are large enough. [https://github.com/gpuweb/gpuweb/pull/678](https://github.com/gpuweb/gpuweb/pull/678) decided that we should require for runtime arrays at least 1 element, so that we can clamp indices. Luckily, there is a function that does this already. This patch adds to the bindings reflection info the minimum buffer size so we can use it in dawn.
The relevant dawn CL is [https://dawn-review.googlesource.com/c/dawn/+/22421](https://dawn-review.googlesource.com/c/dawn/+/22421), which does the same thing using spirv-cross in ShaderModule.cpp.
The variable name can be changed if another one makes more sense?

Add minimum buffer size for dawn reflection

---

libshaderc_spvc/include/spvc/spvc.h
libshaderc_spvc/include/spvc/spvc.hpp
libshaderc_spvc/src/spvc.cc

From https://github.com/KhronosGroup/SPIRV-Cross/issues/1381, HLSL 16-bit types had been introduced by https://github.com/KhronosGroup/SPIRV-Cross/issues/1381. So export the interface in shaderc. Thank you.

Add interface for enabling 16-bit types

---

third_party/CMakeLists.txt

Glslang third party build needs -fPIC

---

DEPS
spvc/test/known_failures
spvc/test/known_spvc_failures

Roll third_party/glslang/ 839704450..f5ed7a69d (30 commits)
https://github.com/KhronosGroup/glslang/compare/839704450200...f5ed7a69d5d6
$ git log 839704450..f5ed7a69d --date=short --no-merges --format='%ad %ae %s'
2020-07-03 marcin.slusarz Add --quiet option.
2020-07-05 ShabbyX gn: Fix dawn tests in Chromium
2020-07-05 ShabbyX gn: Fix `gn gen --check` by adding missing dependency
2020-07-03 bclayton Add GLSLANG_BUILD_PIC CMake flag
2020-07-03 ShabbyX gn: Optionally disable optimizations and HLSL
2020-07-03 bclayton Don't use add_link_options() on old CMake versions
2020-07-03 bclayton License headers: s/Google/The Khronos Group
2020-07-03 bclayton Kokoro: Correct the `build_file' path to build.sh
2020-07-02 bclayton Add config for license-checker and Kokoro scripts.
2020-07-02 bclayton …

Roll 6 dependencies and update expectations.

---

DEPS
third_party/CMakeLists.txt

All glslang targets are now have the `POSITION_INDEPENDENT_CODE` property.
This reverts "Glslang third party build needs -fPIC (#1093)"

Remove pushing / popping -fPIC for glslang 

---

DEPS

Roll third_party/effcee/ 5af957bbf..2ec8f8738 (3 commits)
https://github.com/google/effcee/compare/5af957bbfc7d...2ec8f8738118
$ git log 5af957bbf..2ec8f8738 --date=short --no-merges --format='%ad %ae %s'
2020-06-16 dneto Start v2020.0-dev
2020-06-16 dneto Finalize v2019.1
2020-06-15 dneto Update CHANGES
Created with:
roll-dep third_party/effcee
Roll third_party/glslang/ e8c9fd602..b481744ae (19 commits)
https://github.com/KhronosGroup/glslang/compare/e8c9fd602f11...b481744aea1e
$ git log e8c9fd602..b481744ae --date=short --no-merges --format='%ad %ae %s'
2020-07-14 bclayton Give build_info.py the executable bit
2020-07-14 cepheus Fix recently found non-determinism with gl_WorldToObject3x4EXT.
2020-07-14 cepheus Non-determinism: Remove test file that seems to trigger non-determinism. …

Roll 5 dependencies

---

license-checker.cfg

`license-checker` has been updated to support `**` wildcards simplifying the rules, and multiple license configs.
Add a new config for the `git-sync-deps` file, as this is the only file with a non-apache license type.

Update license-checker.cfg with simplified rules

---

libshaderc_spvc/include/spvc/spvc.h
libshaderc_spvc/include/spvc/spvc.hpp
libshaderc_spvc/src/spvc.cc
spvc/src/main.cc

This includes updating a SPIRV-cross dependency.

Adding support for the additional fixed sample mask in MSL

---

DEPS
spvc/test/known_failures
spvc/test/known_spvc_failures

Roll third_party/glslang/ 3ee5f2f1d..b60e067b4 (8 commits)
https://github.com/KhronosGroup/glslang/compare/3ee5f2f1d331...b60e067b4374
$ git log 3ee5f2f1d..b60e067b4 --date=short --no-merges --format='%ad %ae %s'
2020-08-06 john SPV: Fix #1829: don't emit OpModuleProcessed use-storage-buffer
2020-08-05 john Build/Test: Dropping 2013 allows using the latest googletests.
2020-08-04 john SPV: Standalone; sanity check the client GLSL input semantics option value.
2020-08-04 john SPV: Use more correct SPV-Tools environment, partially addressing #2290
2020-08-04 john SPV: Fix #2363: include trailing newline named text SPV output.
2020-07-03 ShabbyX Use GLSLANG_ANGLE to strip features to what ANGLE requires
2020-07-31 bclayton Revert changes that migrate to `thread_local`.
2020-07-27 dneto Avoid …

Roll 5 dependencies and update expectations

---

libshaderc_spvc/src/spvc_cpp_test.cc
libshaderc_spvc/src/spvc_private.cc
libshaderc_spvc/src/spvc_test.cc

This is a workaround to unblock work going on in Dawn while I finish
off converting Dawn to use the new API.

Add support for Dawn using deprecated Options constructor

---

DEPS

Roll third_party/glslang/ b60e067b4..f257e0ea6 (11 commits)
https://github.com/KhronosGroup/glslang/compare/b60e067b4374...f257e0ea6b9a
$ git log b60e067b4..f257e0ea6 --date=short --no-merges --format='%ad %ae %s'
2020-08-14 john Build: fix a build warning
2020-08-14 rafael.fariasmarinheiro Use --test-root to pass files to Bazel tests.
2020-08-14 john Fix #2366, fix #2358, correctly separate out numerical feature checking
2020-08-14 john Non-functional (almost): Refactor when 'extensionRequested' is called.
2020-08-14 john Non-functional: Remove reinventing the scalar type, note code issues
2020-08-11 john Non-functional: spellings of "destinaton" and "addPairConversion"
2020-08-12 alanbaker Update test expectations
2020-08-12 alanbaker Update SPIRV-Tools and SPIRV-Headers known good …

Roll 4 dependencies

---

DEPS
spvc/test/known_spvc_failures
spvc/test/unconfirmed_invalids

Roll third_party/glslang/ f257e0ea6..983698bb3 (2 commits)
https://github.com/KhronosGroup/glslang/compare/f257e0ea6b9a...983698bb34ec
$ git log f257e0ea6..983698bb3 --date=short --no-merges --format='%ad %ae %s'
2020-08-23 john Revert "Merge pull request #2371 from RafaelMarinheiro/master"
2020-08-21 julius.ikkala Obey ENABLE_PCH CMake option
Created with:
roll-dep third_party/glslang
Roll third_party/googletest/ adeef1929..1e315c5b1 (14 commits)
https://github.com/google/googletest/compare/adeef192947f...1e315c5b1a62
$ git log adeef1929..1e315c5b1 --date=short --no-merges --format='%ad %ae %s'
2020-08-20 absl-team Googletest export
2020-08-17 absl-team Googletest export
2020-08-12 robert.earhart Export LICENSE
2020-08-03 amatanhead Remove ThrowsMessageHasSubstr and fix some nits after …

Roll 4 dependencies and updated expectations

---

DEPS
spvc/test/known_failures
spvc/test/known_spvc_failures

Roll third_party/glslang/ 983698bb3..517f39eee (1 commit)
https://github.com/KhronosGroup/glslang/compare/983698bb34ec...517f39eee46f
$ git log 983698bb3..517f39eee --date=short --no-merges --format='%ad %ae %s'
2020-08-26 jmadill Suppress two override suggestion warnings.
Created with:
roll-dep third_party/glslang
Roll third_party/googletest/ 1e315c5b1..df6b75949 (1 commit)
https://github.com/google/googletest/compare/1e315c5b1a62...df6b75949b1e
$ git log 1e315c5b1..df6b75949 --date=short --no-merges --format='%ad %ae %s'
2020-08-26 absl-team Googletest export
Created with:
roll-dep third_party/googletest
Roll third_party/spirv-tools/ 4dd122392..8a0ebd40f (14 commits)
https://github.com/KhronosGroup/SPIRV-Tools/compare/4dd122392f3a...8a0ebd40f86d
$ git log 4dd122392..8a0ebd40f …

Roll 3 dependencies and update expectations

---

cmake/utils.cmake

When getting the transitive libraries needed for shaderc_combined,
we just deduplicate according to their names. Aliased libraries can
have different names. They can all be packed into shaderc_combined,
which will cause duplicated symbols.
I hit this in https://github.com/google/shaderc-rs, because now in
SPIRV-Tools we have defined the SPIRV-Tools library to alias to
SPIRV-Tools-static.

Handle alias libraries in shaderc_combined to avoid duplicated symbols

---

DEPS

https://github.com/KhronosGroup/glslang/compare/142cb87f803d...7f6559d2802d
$ git log 142cb87f8..7f6559d28 --date=short --no-merges --format='%ad %ae %s'
2020-11-16 ShabbyX Compile out code for GL_EXT_shader_image_int64 for ANGLE (#2463)
2020-11-12 mbechard tweak local_size comparison a bit (#2456)
2020-11-12 dneto Avoid spuriously adding Geometry capability for vert, tesc, tese (#2462)
2020-11-12 greg New nonuniform analysis (#2457)
2020-11-09 jhall1024 Implement GL_EXT_terminate_invocation (#2454)
2020-11-06 rdb Fix token-pasting macros not working in preprocessor directives. (#2453)
2020-11-06 laddoc Fix warning in iomapper. (#2449)
2020-11-04 TobyHector Add GL_EXT_shader_image_int64 support (#2409)
2020-11-04 laddoc 8. io mapping refine & qualifier member check & resolver expand …

Roll third_party/glslang/ 142cb87f8..7f6559d28 (13 commits)

---

DEPS

See
https://www.khronos.org/blog/vulkan-ray-tracing-final-specification-release
Roll third_party/glslang/ 7f6559d28..ffccefddf (1 commit)
https://github.com/KhronosGroup/glslang/compare/7f6559d2802d...ffccefddfd9a
$ git log 7f6559d28..ffccefddf --date=short --no-merges --format='%ad %ae %s'
2020-11-23 dgkoch Updates for final Vulkan ray tracing extensions (#2466)
Created with:
roll-dep third_party/glslang
Roll third_party/spirv-headers/ 5ab5c9619..104ecc356 (4 commits)
https://github.com/KhronosGroup/SPIRV-Headers/compare/5ab5c96198f3...104ecc356c1b
$ git log 5ab5c9619..104ecc356 --date=short --no-merges --format='%ad %ae %s'
2020-11-12 dneto MeshShadingNV enables builtins PrimitiveId, Layer, and ViewportIndex
2020-10-16 dkoch de-alias/reassign OpIgnoreIntersectionKHR/OpTerminateRayKHR …

Roll dependencies to support Vulkan raytracing

---

utils/add_copyright.py

copyright check: Exclude .venv in source tree

---

DEPS

Incorporate SPIRV-Tools fixes for new terminator
instructions in Vulkan raytracing extensions.
https://github.com/KhronosGroup/SPIRV-Tools/pull/4050

Update SPIRV-Tools with raytracing fix

---

DEPS
libshaderc/include/shaderc/env.h
libshaderc/src/shaderc.cc
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/include/libshaderc_util/spirv_tools_wrapper.h
libshaderc_util/src/compiler.cc
libshaderc_util/src/spirv_tools_wrapper.cc

Roll third_party/spirv-tools/ 1bb80d277..ee39b5db5 (16 commits)
https://github.com/KhronosGroup/SPIRV-Tools/compare/1bb80d2778a3...ee39b5db5f1d
$ git log 1bb80d277..ee39b5db5 --date=short --no-merges --format='%ad %ae %s'
2021-01-15 46493288+sfricke-samsung spirv-val: Add Vulkan Addressing Model check (#4107)
2021-01-14 rharrison Remove WebGPU support (#4108)
2021-01-14 46493288+sfricke-samsung spirv-val: Vulkan atomic storage class (#4079)
2021-01-13 jaebaek Avoid integrity check failures caused by propagating line instructions (#4096)
2021-01-13 pierremoreau Linker usability improvements (#4084)
2021-01-12 dj2 Revert "Generate differentiated error codes for buffer oob checking (#4097)" (#4100)
2021-01-11 greg Generate differentiated error codes for buffer oob checking (#4097)
2021-01-07 …

Deprecate WebGPU SPIRV support

---

license-checker.cfg

The golang license library that license-checker uses changed the naming of `Apache-2.0-Header` to `Apache-2.0`.
Update the config to match this change

Update license-checker.cfg with updated license names

---

glslc/src/main.cc
glslc/test/parameter_tests.py

As it appears, the option -g actually has some effect now.

glslc: main.cc: update help: debug info disclaimer

---

libshaderc_util/include/libshaderc_util/string_piece.h

Implicit copy constructors are deprecated and can cause build warnings
or errors with some compilers.

Add explicit copy constructor for string_piece

---

libshaderc_util/src/compiler_test.cc

Found this bug while browsing through the test code. It is passing incorrect shader kind for the test using vertex shader.

Fix shaderc util test to pass the correct shader_stage

---

known_good.json

Shaderc v2021.1
Glslang
SPIRV-Tools v2021.2, plus:
- Fix to symbol checker
- SPV_KHR_integer_dot_product support
SPIRV-Headers

Update known-good commits for dependencies

---

CMakeLists.txt

A Vulkan SDK build of shaderc fails on the copyright check:
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.
CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with co
de 1. [C:\j\msdk\build\shaderc\repo\src\dbuild32\check-copyright.
vcxproj]
Analysis in Visual Studio reveals that the problem is:
20>  .\dbuild\include\glslang\build_info.h  has no copyright mess
age.
20>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microso
ft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with
code 1.
"build_info.h" does indeed have a copyright message:
// Copyright (C) 2020 The Khronos Group Inc.
but this fails the copyright check, which is looking solely for:
Copyright <NNNN> The Shaderc Authors. All rights reserved.
These changes add a …

build: add switch to disable copyright check

---

CHANGES
DEPS
glslc/README.asciidoc
glslc/src/main.cc
glslc/test/expect.py
glslc/test/option_target_spv.py
glslc/test/parameter_tests.py
libshaderc/include/shaderc/env.h
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/src/compiler.cc
libshaderc_util/src/compiler_test.cc

Updates SPIRV-Headers, SPIRV-Tools.
Does not update Glslang or change any internal feature code.
Adds support to target SPIR-V 1.6 code generation.

Update deps to support SPIR-V 1.6, target SPIR-V 1.6 code generation

---

Android.mk
kokoro/ndk-build/build.sh

The GNU binutils have been removed from more recent NDKs.
Use the TARGET_AR and TARGET_STRIP make variables to name
the 'ar' and 'strip' executables, rather than guessing their paths.
Update the ndk-build kokoro build script to test the libshaderc_build
target.

Fix ndk-build libshader_combined target for newer NDK

---

CHANGES
DEPS
glslc/src/main.cc
glslc/test/option_target_env.py
glslc/test/parameter_tests.py
libshaderc/include/shaderc/env.h
libshaderc/src/shaderc.cc
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/src/compiler.cc
libshaderc_util/src/compiler_test.cc
libshaderc_util/src/spirv_tools_wrapper.cc

commit 51d94f91e1b9d66da9c96b8d946bc34e4189f0df
Start v2022.0 development
commit b2a8f99b6753abab2bf8d60a6d4f89f39d4c5694
Finalize v2021.4
commit 9c288704fed0afd4ec9a61b858fa826a4acd8c4c
Support Vulkan 1.3
When compiling to Vulkan 1.3, SPIR-V 1.6 is generated by default.
Update DEPS to point to dependencies supporting Vulkan 1.3
SPIRV-Toosl v2022.1
Glslang as of 2022-01-27

Support Vulkan 1.3, finalize v2021.4, start v2022.0

---

known_good.json

Shaderc v2022.1
SPIRV-Tools v2022.1 plus:
- validator handles Nontemporal image operand
- optimizer handles RayQueryKHR type
Glslang 11.8.0 (vulkan-1.3-B)
SPIRV-Headers (supporting SPIR-V 1.6)

Support Vulkan 1.3

---

CMakeLists.txt

Support for different MSVC Runtime Library options.
Example (when doing cmake setup):
cmake -S ... -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL
May also need to pass additional params to cmake setup:
-DLLVM_USE_CRT_RELEASE=MD
etc.
This is used by glslang (3rd party lib) to configure the MSVC Runtime Library

CMakeLists: enable CMAKE_MSVC_RUNTIME_LIBRARY property

---

CMakeLists.txt

That policy appeared in CMake 3.15
Fixes CI breaks introduced by #1247

Guard CMake policy CMP0091

---

known_good.json

Shaderc v2022.2
Glslang GitHub master 2022-08-11
SPIRV-Headers GitHub master 2022-08-11
SPIRV-Tools v2022.3 plus one patch

Update Shaderc, Glslang, SPIRV-Tools

---

known_good.json

Shaderc v2022.4
Glslang 11.12.0 plus GitHub changes to 2022-11-30
SPIRV-Tools GitHub as of 2022-11-30
SPIRV-Headers GitHub as of 2022-11-30

Update Shaderc, Glslang, SPIRV-Tools, SPIRV-Headers

---

libshaderc_util/include/libshaderc_util/string_piece.h

In C++20, `operator==` candidates include rewritten candidates with reversed operand order, so this function creates infinite recursion just flipping operands back and forth. In C++17, it relies on implicit construction of a `string_piece`.
This is backwards and forwards compatible.

Explicitly construct a `string_piece` when comparing to `char*`

---

CMakeLists.txt

The Khronos ecosystem is moving forward from c++11 to c++17. SPIRV-Tools will update to C++17 soon, hence we need Shaderc to also bump.
See https://github.com/KhronosGroup/SPIRV-Tools/pull/4983

build: move from c++11 to c++17

---

glslc/README.asciidoc
glslc/src/main.cc
glslc/test/option_fpreserve_bindings.py
glslc/test/parameter_tests.py
libshaderc/include/shaderc/shaderc.h
libshaderc/include/shaderc/shaderc.hpp
libshaderc/src/shaderc.cc
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/include/libshaderc_util/spirv_tools_wrapper.h
libshaderc_util/src/compiler.cc
libshaderc_util/src/spirv_tools_wrapper.cc

The new option `-fpreserve-bindings` matches the spirv-option `-preserve-bindings`.
Fixes: https://github.com/google/shaderc/issues/1300

Add option to preserve bindings

---

DEPS

Roll third_party/effcee/ 35912e1b7..66edefd2b (2 commits)
https://github.com/google/effcee/compare/35912e1b7778...66edefd2bb64
$ git log 35912e1b7..66edefd2b --date=short --no-merges --format='%ad %ae %s' 2023-03-02 dneto Avoid hardcoding C++11 requirement at project level 2022-12-20 dneto Update Bazel external dependencies
Created with:
roll-dep third_party/effcee
Roll third_party/glslang/ 1fb2f1d78..2ca0ee3ba (20 commits)
https://github.com/KhronosGroup/glslang/compare/1fb2f1d78966...2ca0ee3ba4ed
$ git log 1fb2f1d78..2ca0ee3ba --date=short --no-merges --format='%ad %ae %s' 2023-02-19 39247600+mjunix Fix potential NULL dereference 2023-02-19 39247600+mjunix Fix potential NULL dereference 2023-02-15 moritz.heinemann move ResourceLimits from StandAlone to glslang dir (Fix #3064) 2023-02-08 …

Roll dependencies

---

Android.mk
README.md
kokoro/ndk-build/build.sh

Fixes building of combined.ar on Windows.
Fixes #1321
Additionally:
- Use generate-file-dir macro This saves calling 'mkdir -p' repeatedly for each file.
- Simplify header generation logic
- Avoid a useless eval. Invoke the combined lib rules on TARGET_OUT directly.
Update NDK dependency to Android NDK 21d
- The ndk-build is based on GNU make 4. We need that to support the $(file ...) function

Android.mk: Use $(file ..) instead of raw @echo. Update to NDK 21d

---

.gitignore
DEPS
third_party/CMakeLists.txt

The latest version of RE2 depends on Abseil. This add Abseil as a dep
for shaderc, and updates RE2 to make sure it works.
This is needed to fix the spirv-tools smoke test.

Add abseil as a dep

---

kokoro/android-release/build-docker.sh
kokoro/ndk-build/build-docker.sh

We currently use R21 of the Android NDK for our tests. There have been
to LTS release since that one, and we do not expect people to use it
anymore. Also, it contains Python 2.7, not Python3. The python scripts
in SPIR-V Tools expect Python 3, so we have to update.
We chose the latest LTS release.

Use android ndk r25

---

CMakeLists.txt

3.15 no longer appends /MD to the C_FLAGS and CXX_FLAGS by default when using the policy CMP0091 with the new behavior. This breaks any existing CMake code which searched for "/MD" to replace it with "/MT", as the flags no longer contain /MD. The fix is to use the new property MSVC_RUNTIME_LIBRARY so that all targets are configured correctly.
Fixes #1337

Fix MSVC runtime library linking in CMake

---

third_party/CMakeLists.txt

MSVC 2017 debug build requires /bigobj for SPIRV-Tools test_opt

---

CHANGES
DEPS
utils/update_build_version.py

Also teach the build version extractor to understand [\.-]rc\d+ suffices.

Make release candidate v2023.5-rc1

---

README.md
kokoro/linux/build-docker.sh

When compiling with MinGW, we no longer need to use -Dgtest_disable_pthreads=ON.
See https://github.com/google/googletest/pull/856
and https://github.com/google/googletest/pull/721

Remove redundant gtest compile flags for MinGW

---

DEPS
libshaderc/src/shaderc_cpp_test.cc

Update SPIRV-Tools
The SPIRV-Tools message has changed, for the case when a capability was used that is not appropriate to the current target environment.

Adapt test to different error message from SPIRV-Tools

---

.github/workflows/autoroll.yml
utils/roll-deps

Create a GitHub action that syncs all git dependencies, rolls all entries in DEPS to tip-of-tree and commits, then uploads a new GitHub pull request with a trigger to automatically run kokoro tests.
The roll-deps script has been updated to not return an error when there are no new commits for a repository.
Both the autoroll.yml script and changes to utils/roll-deps are modeled after the scripts in KhronosGroup/SPIRV-Tools.

Add a workflow to automatically roll DEPS

---

CHANGES
DEPS

Start Shaderc v2023.8-dev
commit 468b152c92ffb2e7b2950822aa3456363f46c184
Author: David Neto <dneto@google.com>
Date:   Thu Oct 12 21:22:29 2023 -0400
Shaderc v2303.7 release
commit fed6f087405fc49800d478824ff30638550048af
Author: David Neto <dneto@google.com>
Date:   Thu Oct 12 21:17:43 2023 -0400
Make Shaderc v2023.7-rc1 release candidate
commit 0b4ee9ac0f1d8833aee8caf2192986fa75a56a2c
Author: David Neto <dneto@google.com>
Date:   Thu Oct 12 21:12:49 2023 -0400
Update DEPS
Glslang GitHub top of tree 2023-10-12
SPIRV-Tools v2023.5.rc1
SPIRV-Headers GitHub top of tree 2023-10-12

Make Shaderc v2023.7 release

---

cmake/utils.cmake
libshaderc/CMakeLists.txt

Rather than trying to manually merge static libraries into a combined static library, we can instead just let CMake do it for us.
This solves:
- https://github.com/google/shaderc/issues/1367
- https://github.com/google/shaderc/issues/473
I've successfully tested this with the following generators:
- Visual Studio 17 2022
- Unix Makefiles
- Ninja
- Ninja Multi-Config
- CodeBlocks - Ninja
- CodeBlocks - Unix Makefiles
- CodeLite - Ninja
- CodeLite - Unix Makefiles
- Eclipse CDT4 - Ninja
- Eclipse CDT4 - Unix Makefiles
- Kate - Ninja
- Kate - Unix Makefiles
- Sublime Text 2 - Ninja
- Sublime Text 2 - Unix Makefiles

CMake: Use TARGET_OBJECTS to replace archive acrobatics

---

.gitignore
libshaderc/include/shaderc/shaderc.h
libshaderc/include/shaderc/shaderc.hpp
libshaderc/src/shaderc.cc
libshaderc_util/include/libshaderc_util/compiler.h
libshaderc_util/src/compiler.cc
libshaderc_util/src/compiler_test.cc

This exposes https://github.com/KhronosGroup/GLSL/blob/master/extensions/ext/GL_EXT_vulkan_glsl_relaxed.txt, which allows for compilation of many OpenGL GLSL shaders to Vulkan SPIRV.
Adds a simple test.

Expose setting relaxed Vulkan rules from glslang

---

libshaderc/include/shaderc/shaderc.hpp

"Sets whether the compiler should generates code for max an min" -> "Sets whether the compiler should generate code for max and min"

Fix comment typo in shaderc.hpp

---

DEPS
glslc/test/option_fresource_set_binding.py

React to https://github.com/KhronosGroup/glslang/pull/3635 which deduplicates decorations on an object.  It has the side effect of ordering decorations on an object by the decoration enum.

Fix expectations: Glslang orders decorations on an object by enum

---

glslc/test/option_mfmt.py

This fixes warnings in more recent python versions.

Fix Python string escapes

---

kokoro/linux/build-docker.sh

kokoro: use Python 3.12 on Linux

---

libshaderc_util/src/spirv_tools_wrapper.cc

Setting up friendly names requires parsing the entire module
which costs a lot of time due to (1) scanning the whole module,
and (2) creating string names for many IDs.
This is a followup to https://github.com/KhronosGroup/SPIRV-Tools/issues/5802
There, Blender was suffering long shader suite build times due to
serialization on locale. But secondarily we noticed there was a lot
of string manipulation when setting up the validator, all because
the friendly name mapper is on by default for the optimizer.
Turn off friendly names in the optimizer's use of the validator.
The validation errors are only emitted when there is a compiler
bug, so they should be rare.  Don't make every compilation pay
the cost.

Don't use friendly names for SPIR-V validation errors

---

DEPS

These now use the 'alias' mechanism in the SPIR-V json grammar. See https://github.com/KhronosGroup/SPIRV-Headers/pull/447 and https://github.com/KhronosGroup/SPIRV-Tools/pull/5799

Update SPIRV-Tools, SPIRV-Headers

---

DEPS
kokoro/android-release/build-docker.sh
kokoro/linux/build-docker.sh
kokoro/windows/build.bat

SPIRV-Tools fixes
- validation of multi-line debug info.
- assembler: avoid infinite loop when trying to parse version string from comments

Update glslang, SPIRV-Tools

---

DEPS

Effcee uses the new CMake method for setting the MSVC runtime CMP0091 NEW

Update effcee, spirv-tools

---

kokoro/windows/build.bat
kokoro/windows/build_2019_amd64_debug.bat
kokoro/windows/build_2019_amd64_release.bat
kokoro/windows/build_2022_amd64_debug.bat
kokoro/windows/build_2022_amd64_release.bat
kokoro/windows/continuous_debug_2019.cfg
kokoro/windows/continuous_release_2019.cfg
kokoro/windows/presubmit_debug_2019.cfg
kokoro/windows/vs2022_amd64_debug_continuous.cfg
kokoro/windows/vs2022_amd64_debug_presubmit.cfg
kokoro/windows/vs2022_amd64_release_continuous.cfg
kokoro/windows/vs2022_amd64_release_presubmit.cfg

Refactor how files and scripts are named.
Add an %ARCH% argument to the build script, in anticipation of adding arm64 builds later.

kokoro: add VS2022 scripts
